---
title: "OUT_analisis2"
author: "Opamelas83"
date: "2022-03-16"
output: workflowr::wflow_html
editor_options:
  chunk_output_type: console
---

## use PRcomp function to check the difference between simulated and observed data across environment

```{r}
library(DSSAT)
library(tidyverse)
library(data.table)
library(corrplot)
TralList <- dir()[dir()%like%".CSX"]
```

```{r}
  for(x in TralList){
      Tral <- read_lines(x)
      strtTrt <- grep(pattern = "*TREATMENTS", x = Tral, fixed=T)+2
      endTrt <- grep(pattern = "*CULTIVARS", x = Tral, fixed=T)-2
      Tral <- Tral[strtTrt:endTrt]
      Tral <- substr(Tral, start = 10, stop = 37)
      write.table(Tral, "test.txt", quote = F, col.names = F, row.names = F)
      Tral <- read.table("test.txt", header =F)
      colnames(Tral) <- c("Clone", "TRNO")
    
    MYYY <- here::here("data", "ClonTRNO", paste0(substr(x, 1,8), ".csv"))
    write.csv(x = Tral, file = MYYY, row.names = F)
}

```

##Run dscsm (next time, Try to run dscsm for all treatment )

```{r}
write_dssbatch("UYAB1901.CSX", trtno = 1:67)
run_dssat(suppress_output = TRUE)
# From evaluate output file
OUT1 <- read_output((here::here("Evaluate.OUT")), col_types = NULL, 
                               col_names = NULL, 
                             left_justified = NULL, 
              read_only = NULL,  store_v_fmt = FALSE)
OUT_UYAB1901 <- OUT1 %>% dplyr::select(EXCODE, TRNO, HWAMS, HWAMM, LAIXS, LAIXM, CWAMS, CWAMM)
Gernam <- read_csv("data/ClonTRNO/UYAB1901.csv")
DUYAB1901 <- left_join(Gernam, OUT_UYAB1901)

## from weather output file 
OUT2 <- read_output((here::here("Weather.OUT")), col_types = NULL, 
                               col_names = NULL, 
                             left_justified = NULL, 
              read_only = NULL,  store_v_fmt = FALSE)
OUTweath_UYAB1901 <- OUT2 %>% slice(1:406) %>% 
                 mutate(TMAX = TMXD, TMIN = TMND, RAIN = PRED, 
                        PAR = PARD, WIND = WDSD) %>%
             dplyr::select(TMIN, TMAX, RAIN, SRAD, PAR, WIND)

HUMID1 <- read_lines(here::here("UYAB1704.WTH"), skip = 903, n_max = 406)
write_lines(HUMID1, (here::here("HUMIDUS.txt")))
HUMIDEC <- read.table(here::here("HUMIDUS.txt"), header = FALSE, sep = "", dec = ".")
HUMID2 <- HUMIDEC %>% mutate(TMAX = V4, TMIN = V3, RH2M = V6)%>% 
                       dplyr::select(TMAX, TMIN, RH2M) 
OUTweath_UYAB1901 <- left_join(OUTweath_UYAB1901, HUMID2)
#Merge column
DUYAB1901$TMIN <- mean(OUTweath_UYAB1901$TMIN, na.rm = TRUE)
DUYAB1901$TMAX <- mean(OUTweath_UYAB1901$TMAX, na.rm = TRUE)
DUYAB1901$SRAD <- mean(OUTweath_UYAB1901$SRAD, na.rm = TRUE)
DUYAB1901$PAR <- mean(OUTweath_UYAB1901$PAR, na.rm = TRUE)
DUYAB1901$RH2M <- mean(OUTweath_UYAB1901$RH2M, na.rm = TRUE)
DUYAB1901$WIND <- mean(OUTweath_UYAB1901$WIND, na.rm = TRUE)
DUYAB1901$RAIN <- sum(OUTweath_UYAB1901$RAIN)
DUYAB1901$ELEV <- 406.97
DUYAB1901$LAT <- 9.0738
DUYAB1901$LONG <- 7.4651
```

```{r}
write_dssbatch("UYAG1701.CSX", trtno = 1:36)
run_dssat(suppress_output = TRUE)
OUT1 <- read_output((here::here("Evaluate.OUT")), col_types = NULL, 
                               col_names = NULL, 
                             left_justified = NULL, 
              read_only = NULL,  store_v_fmt = FALSE)
OUT_UYAG1701 <- OUT1 %>% dplyr::select(EXCODE, TRNO, HWAMS, HWAMM, LAIXS, LAIXM, CWAMS, CWAMM)

Gernam <- read_csv("data/ClonTRNO/UYAG1701.csv")
DUYAG1701 <- left_join(Gernam, OUT_UYAG1701)
## from weather output file 
OUT2 <- read_output((here::here("Weather.OUT")), col_types = NULL, 
                               col_names = NULL, 
                             left_justified = NULL, 
              read_only = NULL,  store_v_fmt = FALSE)
OUTweath_UYAG1701 <- OUT2 %>% slice(1:317) %>% 
                 mutate(TMAX = TMXD, TMIN = TMND, RAIN = PRED, 
                        PAR = PARD, WIND = WDSD) %>%
             dplyr::select(TMIN, TMAX, RAIN, SRAD, PAR, WIND)

HUMID1 <- read_lines(here::here("UYOW1704.WTH"), skip = 246, n_max = 317)
write_lines(HUMID1, (here::here("HUMIDUS.txt")))
HUMIDEC <- read.table(here::here("HUMIDUS.txt"), header = FALSE, sep = "", dec = ".")
HUMID2 <- HUMIDEC %>% mutate(TMAX = V4, TMIN = V3, RH2M = V6)%>% 
                       dplyr::select(TMAX, TMIN, RH2M) 
OUTweath_UYAG1701 <- left_join(OUTweath_UYAG1701, HUMID2)

#Merge column
DUYAG1701$TMIN <- mean(OUTweath_UYAG1701$TMIN, na.rm = TRUE)
DUYAG1701$TMAX <- mean(OUTweath_UYAG1701$TMAX, na.rm = TRUE)
DUYAG1701$SRAD <- mean(OUTweath_UYAG1701$SRAD, na.rm = TRUE)
DUYAG1701$PAR <- mean(OUTweath_UYAG1701$PAR, na.rm = TRUE)
DUYAG1701$RH2M <- mean(OUTweath_UYAG1701$RH2M, na.rm = TRUE)
DUYAG1701$WIND <- mean(OUTweath_UYAG1701$WIND, na.rm = TRUE)
DUYAG1701$RAIN <- sum(OUTweath_UYAG1701$RAIN)
DUYAG1701$ELEV <- 256.41
DUYAG1701$LAT <- 7.2552
DUYAG1701$LONG <- 4.3225
```


```{r}
write_dssbatch("UYAG1801.CSX", trtno = 1:36)
run_dssat(suppress_output = TRUE)
OUT1 <- read_output((here::here("Evaluate.OUT")), col_types = NULL, 
                               col_names = NULL, 
                             left_justified = NULL, 
              read_only = NULL,  store_v_fmt = FALSE)
OUT_UYAG1801 <- OUT1 %>% dplyr::select(EXCODE, TRNO, HWAMS, HWAMM, LAIXS, LAIXM, CWAMS, CWAMM)

Gernam <- read_csv("data/ClonTRNO/UYAG1801.csv")
DUYAG1801 <- left_join(Gernam, OUT_UYAG1801)

## from weather output file 
OUT2 <- read_output((here::here("Weather.OUT")), col_types = NULL, 
                               col_names = NULL, 
                             left_justified = NULL, 
              read_only = NULL,  store_v_fmt = FALSE)
OUTweath_UYAG1801 <- OUT2 %>% slice(1:366) %>% 
                 mutate(TMAX = TMXD, TMIN = TMND, RAIN = PRED, 
                        PAR = PARD, WIND = WDSD) %>%
             dplyr::select(TMIN, TMAX, RAIN, SRAD, PAR, WIND)

HUMID1 <- read_lines(here::here("UYOW1704.WTH"), skip = 541, n_max = 366)
write_lines(HUMID1, (here::here("HUMIDUS.txt")))
HUMIDEC <- read.table(here::here("HUMIDUS.txt"), header = FALSE, sep = "", dec = ".")
HUMID2 <- HUMIDEC %>% mutate(TMAX = V4, TMIN = V3, RH2M = V6)%>% 
                       dplyr::select(TMAX, TMIN, RH2M)  
OUTweath_UYAG1801 <- left_join(OUTweath_UYAG1801, HUMID2)

#Merge column
DUYAG1801$TMIN <- mean(OUTweath_UYAG1801$TMIN, na.rm = TRUE)
DUYAG1801$TMAX <- mean(OUTweath_UYAG1801$TMAX, na.rm = TRUE)
DUYAG1801$SRAD <- mean(OUTweath_UYAG1801$SRAD, na.rm = TRUE)
DUYAG1801$PAR <- mean(OUTweath_UYAG1801$PAR, na.rm = TRUE)
DUYAG1801$RH2M <- mean(OUTweath_UYAG1801$RH2M, na.rm = TRUE)
DUYAG1801$WIND<- mean(OUTweath_UYAG1801$WIND, na.rm = TRUE)
DUYAG1801$RAIN <- sum(OUTweath_UYAG1801$RAIN)
DUYAG1801$ELEV <- 256.41
DUYAG1801$LAT <- 7.2552
DUYAG1801$LONG <- 4.3225
```

```{r}
write_dssbatch("UYAG1901.CSX", trtno = 1:36)
run_dssat(suppress_output = TRUE)
OUT1 <- read_output((here::here("Evaluate.OUT")), col_types = NULL, 
                               col_names = NULL, 
                             left_justified = NULL, 
              read_only = NULL,  store_v_fmt = FALSE)
OUT_UYAG1901 <- OUT1 %>% dplyr::select(EXCODE, TRNO, HWAMS, HWAMM, LAIXS, LAIXM, CWAMS, CWAMM)

Gernam <- read_csv("data/ClonTRNO/UYAG1901.csv")
DUYAG1901 <- left_join(Gernam, OUT_UYAG1901)

## from weather output file 
OUT2 <- read_output((here::here("Weather.OUT")), col_types = NULL, 
                               col_names = NULL, 
                             left_justified = NULL, 
              read_only = NULL,  store_v_fmt = FALSE)
OUTweath_UYAG1901 <- OUT2 %>% slice(1:367) %>% 
                 mutate(TMAX = TMXD, TMIN = TMND, RAIN = PRED, 
                        PAR = PARD, WIND = WDSD) %>%
             dplyr::select(TMIN, TMAX, RAIN, SRAD, PAR, WIND)

HUMID1 <- read_lines(here::here("UYOW1704.WTH"), skip = 885, n_max = 367)
write_lines(HUMID1, (here::here("HUMIDUS.txt")))
HUMIDEC <- read.table(here::here("HUMIDUS.txt"), header = FALSE, sep = "", dec = ".")
HUMID2 <- HUMIDEC %>% mutate(TMAX = V4, TMIN = V3, RH2M = V6)%>% 
                       dplyr::select(TMAX, TMIN, RH2M)  
OUTweath_UYAG1901 <- left_join(OUTweath_UYAG1901, HUMID2)

#Merge column
DUYAG1901$TMIN <- mean(OUTweath_UYAG1901$TMIN, na.rm = TRUE)
DUYAG1901$TMAX <- mean(OUTweath_UYAG1901$TMAX, na.rm = TRUE)
DUYAG1901$SRAD <- mean(OUTweath_UYAG1901$SRAD, na.rm = TRUE)
DUYAG1901$PAR <- mean(OUTweath_UYAG1901$PAR, na.rm = TRUE)
DUYAG1901$RAIN <- sum(OUTweath_UYAG1901$RAIN)
DUYAG1901$RH2M <- mean(OUTweath_UYAG1901$RH2M, na.rm = TRUE)
DUYAG1901$WIND <- mean(OUTweath_UYAG1901$WIND, na.rm = TRUE)
DUYAG1901$ELEV <- 256.41
DUYAG1901$LAT <- 7.2552
DUYAG1901$LONG <- 4.3225
```

```{r}
write_dssbatch("UYIB1701.CSX", trtno = 1:33)
run_dssat(suppress_output = TRUE)
OUT1 <- read_output((here::here("Evaluate.OUT")), col_types = NULL, 
                               col_names = NULL, 
                             left_justified = NULL, 
              read_only = NULL,  store_v_fmt = FALSE)
OUT_UYIB1701 <- OUT1 %>% dplyr::select(EXCODE, TRNO, HWAMS, HWAMM, LAIXS, LAIXM, CWAMS, CWAMM)

Gernam <- read_csv("data/ClonTRNO/UYIB1701.csv")
DUYIB1701 <- left_join(Gernam, OUT_UYIB1701)
## from weather output file 
OUT2 <- read_output((here::here("Weather.OUT")), col_types = NULL, 
                               col_names = NULL, 
                             left_justified = NULL, 
              read_only = NULL,  store_v_fmt = FALSE)
OUTweath_UYIB1701 <- OUT2 %>% slice(1:366) %>% 
                 mutate(TMAX = TMXD, TMIN = TMND, RAIN = PRED, 
                        PAR = PARD, WIND = WDSD) %>%
             dplyr::select(TMIN, TMAX, RAIN, SRAD, PAR, WIND)

HUMID1 <- read_lines(here::here("UYIB1704.WTH"), skip = 255, n_max = 366)
write_lines(HUMID1, (here::here("HUMIDUS.txt")))
HUMIDEC <- read.table(here::here("HUMIDUS.txt"), header = FALSE, sep = "", dec = ".")
HUMID2 <- HUMIDEC %>% mutate(TMAX = V4, TMIN = V3, RH2M = V6)%>% 
                       dplyr::select(TMAX, TMIN, RH2M)  
OUTweath_UYIB1701 <- left_join(OUTweath_UYIB1701, HUMID2)

#Merge column
DUYIB1701$TMIN <- mean(OUTweath_UYIB1701$TMIN, na.rm = TRUE)
DUYIB1701$TMAX <- mean(OUTweath_UYIB1701$TMAX, na.rm = TRUE)
DUYIB1701$SRAD <- mean(OUTweath_UYIB1701$SRAD, na.rm = TRUE)
DUYIB1701$PAR <- mean(OUTweath_UYIB1701$PAR, na.rm = TRUE)
DUYIB1701$RH2M <- mean(OUTweath_UYIB1701$RH2M, na.rm = TRUE)
DUYIB1701$WIND <- mean(OUTweath_UYIB1701$WIND, na.rm = TRUE)
DUYIB1701$RAIN <- sum(OUTweath_UYIB1701$RAIN)
DUYIB1701$ELEV <- 189
DUYIB1701$LAT <- 7.4661
DUYIB1701$LONG <- 3.9302
```

```{r}
write_dssbatch("UYIB1801.CSX", trtno = 1:57)
run_dssat(suppress_output = TRUE)
OUT1 <- read_output((here::here("Evaluate.OUT")), col_types = NULL, 
                               col_names = NULL, 
                             left_justified = NULL, 
              read_only = NULL,  store_v_fmt = FALSE)
OUT_UYIB1801 <- OUT1 %>% dplyr::select(EXCODE, TRNO, HWAMS, HWAMM, LAIXS, LAIXM, CWAMS, CWAMM)

Gernam <- read_csv("data/ClonTRNO/UYIB1801.csv")
DUYIB1801 <- left_join(Gernam, OUT_UYIB1801)

## from weather output file 
OUT2 <- read_output((here::here("Weather.OUT")), col_types = NULL, 
                               col_names = NULL, 
                             left_justified = NULL, 
              read_only = NULL,  store_v_fmt = FALSE)
OUTweath_UYIB1801 <- OUT2 %>% slice(1:366) %>% 
                 mutate(TMAX = TMXD, TMIN = TMND, RAIN = PRED, 
                        PAR = PARD, WIND = WDSD) %>%
             dplyr::select(TMIN, TMAX, RAIN, SRAD, PAR, WIND)

HUMID1 <- read_lines(here::here("UYIB1704.WTH"), skip = 620, n_max = 366)
write_lines(HUMID1, (here::here("HUMIDUS.txt")))
HUMIDEC <- read.table(here::here("HUMIDUS.txt"), header = FALSE, sep = "", dec = ".")
HUMID2 <- HUMIDEC %>% mutate(TMAX = V4, TMIN = V3, RH2M = V6)%>% 
                       dplyr::select(TMAX, TMIN, RH2M)  
OUTweath_UYIB1801 <- left_join(OUTweath_UYIB1801, HUMID2)

#Merge column
DUYIB1801$TMIN <- mean(OUTweath_UYIB1801$TMIN, na.rm = TRUE)
DUYIB1801$TMAX <- mean(OUTweath_UYIB1801$TMAX, na.rm = TRUE)
DUYIB1801$SRAD <- mean(OUTweath_UYIB1801$SRAD, na.rm = TRUE)
DUYIB1801$PAR <- mean(OUTweath_UYIB1801$PAR, na.rm = TRUE)
DUYIB1801$RH2M <- mean(OUTweath_UYIB1801$RH2M, na.rm = TRUE)
DUYIB1801$WIND <- mean(OUTweath_UYIB1801$WIND, na.rm = TRUE)
DUYIB1801$RAIN <- sum(OUTweath_UYIB1801$RAIN)
DUYIB1801$ELEV <- 189
DUYIB1801$LAT <- 7.4661
DUYIB1801$LONG <- 3.9302
```

```{r}
write_dssbatch("UYIB1901.CSX", trtno = 1:66)
run_dssat(suppress_output = TRUE)
OUT1 <- read_output((here::here("Evaluate.OUT")), col_types = NULL, 
                               col_names = NULL, 
                             left_justified = NULL, 
              read_only = NULL,  store_v_fmt = FALSE)
OUT_UYIB1901 <- OUT1 %>% dplyr::select(EXCODE, TRNO, HWAMS, HWAMM, LAIXS, LAIXM, CWAMS, CWAMM)

Gernam <- read_csv("data/ClonTRNO/UYIB1901.csv")
DUYIB1901 <- left_join(Gernam, OUT_UYIB1901)

## from weather output file 
OUT2 <- read_output((here::here("Weather.OUT")), col_types = NULL, 
                               col_names = NULL, 
                             left_justified = NULL, 
              read_only = NULL,  store_v_fmt = FALSE)
OUTweath_UYIB1901 <- OUT2 %>% slice(1:341) %>% 
                 mutate(TMAX = TMXD, TMIN = TMND, RAIN = PRED, 
                        PAR = PARD, WIND = WDSD) %>%
             dplyr::select(TMIN, TMAX, RAIN, SRAD, PAR, WIND)

HUMID1 <- read_lines(here::here("UYIB1704.WTH"), skip = 869, n_max = 341)
write_lines(HUMID1, (here::here("HUMIDUS.txt")))
HUMIDEC <- read.table(here::here("HUMIDUS.txt"), header = FALSE, sep = "", dec = ".")
HUMID2 <- HUMIDEC %>% mutate(TMAX = V4, TMIN = V3, RH2M = V6)%>% 
                       dplyr::select(TMAX, TMIN, RH2M)  
OUTweath_UYIB1901 <- left_join(OUTweath_UYIB1901, HUMID2)

#Merge column
DUYIB1901$TMIN <- mean(OUTweath_UYIB1901$TMIN, na.rm = TRUE)
DUYIB1901$TMAX <- mean(OUTweath_UYIB1901$TMAX, na.rm = TRUE)
DUYIB1901$SRAD <- mean(OUTweath_UYIB1901$SRAD, na.rm = TRUE)
DUYIB1901$PAR <- mean(OUTweath_UYIB1901$PAR, na.rm = TRUE)
DUYIB1901$RH2M <- mean(OUTweath_UYIB1901$RH2M, na.rm = TRUE)
DUYIB1901$WIND <- mean(OUTweath_UYIB1901$WIND, na.rm = TRUE)
DUYIB1901$RAIN <- sum(OUTweath_UYIB1901$RAIN)
DUYIB1901$ELEV <- 189
DUYIB1901$LAT <- 7.4661
DUYIB1901$LONG <- 3.9302
```


```{r}
write_dssbatch("UYIK1701.CSX", trtno = 1:67)
run_dssat(suppress_output = TRUE)
OUT1 <- read_output((here::here("Evaluate.OUT")), col_types = NULL, 
                               col_names = NULL, 
                             left_justified = NULL, 
              read_only = NULL,  store_v_fmt = FALSE)
OUT_UYIK1701 <- OUT1 %>% dplyr::select(EXCODE, TRNO, HWAMS, HWAMM, LAIXS, LAIXM, CWAMS, CWAMM)

Gernam <- read_csv("data/ClonTRNO/UYIK1701.csv")
DUYIK1701 <- left_join(Gernam, OUT_UYIK1701)

## from weather output file 
OUT2 <- read_output((here::here("Weather.OUT")), col_types = NULL, 
                               col_names = NULL, 
                             left_justified = NULL, 
              read_only = NULL,  store_v_fmt = FALSE)
OUTweath_UYIK1701 <- OUT2 %>% slice(1:371) %>% 
                 mutate(TMAX = TMXD, TMIN = TMND, RAIN = PRED, 
                        PAR = PARD, WIND = WDSD) %>%
             dplyr::select(TMIN, TMAX, RAIN, SRAD, PAR, WIND)

HUMID1 <- read_lines(here::here("UYIK1704.WTH"), skip = 240, n_max = 371)
write_lines(HUMID1, (here::here("HUMIDUS.txt")))
HUMIDEC <- read.table(here::here("HUMIDUS.txt"), header = FALSE, sep = "", dec = ".")
HUMID2 <- HUMIDEC %>% mutate(TMAX = V4, TMIN = V3, RH2M = V6)%>% 
                       dplyr::select(TMAX, TMIN, RH2M)  
OUTweath_UYIK1701 <- left_join(OUTweath_UYIK1701, HUMID2)

#Merge column
DUYIK1701$TMIN <- mean(OUTweath_UYIK1701$TMIN, na.rm = TRUE)
DUYIK1701$TMAX <- mean(OUTweath_UYIK1701$TMAX, na.rm = TRUE)
DUYIK1701$SRAD <- mean(OUTweath_UYIK1701$SRAD, na.rm = TRUE)
DUYIK1701$PAR <- mean(OUTweath_UYIK1701$PAR, na.rm = TRUE)
DUYIK1701$RH2M <- mean(OUTweath_UYIK1701$RH2M, na.rm = TRUE)
DUYIK1701$WIND <- mean(OUTweath_UYIK1701$WIND, na.rm = TRUE)
DUYIK1701$RAIN <- sum(OUTweath_UYIK1701$RAIN)
DUYIK1701$ELEV <- 91
DUYIK1701$LAT <- 6.8728
DUYIK1701$LONG <- 3.7108
```

```{r}
write_dssbatch("UYIK1801.CSX", trtno = 1:67)
run_dssat(suppress_output = TRUE)
OUT1 <- read_output((here::here("Evaluate.OUT")), col_types = NULL, 
                               col_names = NULL, 
                             left_justified = NULL, 
              read_only = NULL,  store_v_fmt = FALSE)
OUT_UYIK1801 <- OUT1 %>% dplyr::select(EXCODE, TRNO, HWAMS, HWAMM, LAIXS, LAIXM, CWAMS, CWAMM)

Gernam <- read_csv("data/ClonTRNO/UYIK1801.csv")
DUYIK1801 <- left_join(Gernam, OUT_UYIK1801)

## from weather output file 
OUT2 <- read_output((here::here("Weather.OUT")), col_types = NULL, 
                               col_names = NULL, 
                             left_justified = NULL, 
              read_only = NULL,  store_v_fmt = FALSE)
OUTweath_UYIK1801 <- OUT2 %>% slice(1:366) %>% 
                 mutate(TMAX = TMXD, TMIN = TMND, RAIN = PRED, 
                        PAR = PARD, WIND = WDSD) %>%
             dplyr::select(TMIN, TMAX, RAIN, SRAD, PAR, WIND)

HUMID1 <- read_lines(here::here("UYIK1704.WTH"), skip = 537, n_max = 366)
write_lines(HUMID1, (here::here("HUMIDUS.txt")))
HUMIDEC <- read.table(here::here("HUMIDUS.txt"), header = FALSE, sep = "", dec = ".")
HUMID2 <- HUMIDEC %>% mutate(TMAX = V4, TMIN = V3, RH2M = V6)%>% 
                       dplyr::select(TMAX, TMIN, RH2M)  
OUTweath_UYIK1801 <- left_join(OUTweath_UYIK1801, HUMID2)

#Merge column
DUYIK1801$TMIN <- mean(OUTweath_UYIK1801$TMIN, na.rm = TRUE)
DUYIK1801$TMAX <- mean(OUTweath_UYIK1801$TMAX, na.rm = TRUE)
DUYIK1801$SRAD <- mean(OUTweath_UYIK1801$SRAD, na.rm = TRUE)
DUYIK1801$PAR <- mean(OUTweath_UYIK1801$PAR, na.rm = TRUE)
DUYIK1801$RH2M <- mean(OUTweath_UYIK1801$RH2M, na.rm = TRUE)
DUYIK1801$WIND <- mean(OUTweath_UYIK1801$WIND, na.rm = TRUE)
DUYIK1801$RAIN <- sum(OUTweath_UYIK1801$RAIN)
DUYIK1801$ELEV <- 91
DUYIK1801$LAT <- 6.8728
DUYIK1801$LONG <- 3.7108
```

```{r}
write_dssbatch("UYIK1901.CSX", trtno = 1:67)
run_dssat(suppress_output = TRUE)
OUT1 <- read_output((here::here("Evaluate.OUT")), col_types = NULL, 
                               col_names = NULL, 
                             left_justified = NULL, 
              read_only = NULL,  store_v_fmt = FALSE)
OUT_UYIK1901 <- OUT1 %>% dplyr::select(EXCODE, TRNO, HWAMS, HWAMM, LAIXS, LAIXM, CWAMS, CWAMM)

Gernam <- read_csv("data/ClonTRNO/UYIK1901.csv")
DUYIK1901 <- left_join(Gernam, OUT_UYIK1901)

## from weather output file 
OUT2 <- read_output((here::here("Weather.OUT")), col_types = NULL, 
                               col_names = NULL, 
                             left_justified = NULL, 
              read_only = NULL,  store_v_fmt = FALSE)
OUTweath_UYIK1901 <- OUT2 %>% slice(1:381) %>% 
                 mutate(TMAX = TMXD, TMIN = TMND, RAIN = PRED, 
                        PAR = PARD, WIND = WDSD) %>%
             dplyr::select(TMIN, TMAX, RAIN, SRAD, PAR, WIND)

HUMID1 <- read_lines(here::here("UYIK1704.WTH"), skip = 885, n_max = 381)
write_lines(HUMID1, (here::here("HUMIDUS.txt")))
HUMIDEC <- read.table(here::here("HUMIDUS.txt"), header = FALSE, sep = "", dec = ".")
HUMID2 <- HUMIDEC %>% mutate(TMAX = V4, TMIN = V3, RH2M = V6)%>% 
                       dplyr::select(TMAX, TMIN, RH2M)  
OUTweath_UYIK1901 <- left_join(OUTweath_UYIK1901, HUMID2)

#Merge column
DUYIK1901$TMIN <- mean(OUTweath_UYIK1901$TMIN, na.rm = TRUE)
DUYIK1901$TMAX <- mean(OUTweath_UYIK1901$TMAX, na.rm = TRUE)
DUYIK1901$SRAD <- mean(OUTweath_UYIK1901$SRAD, na.rm = TRUE)
DUYIK1901$PAR <- mean(OUTweath_UYIK1901$PAR, na.rm = TRUE)
DUYIK1901$RH2M <- mean(OUTweath_UYIK1901$RH2M, na.rm = TRUE)
DUYIK1901$WIND <- mean(OUTweath_UYIK1901$WIND, na.rm = TRUE)
DUYIK1901$RAIN <- sum(OUTweath_UYIK1901$RAIN)
DUYIK1901$ELEV <- 91
DUYIK1901$LAT <- 6.8728
DUYIK1901$LONG <- 3.7108
```

Not run
```{r}
#write_dssbatch("UYKA1801.CSX", trtno = 1:61)
#run_dssat(suppress_output = TRUE)
#OUT1 <- read_output((here::here("Evaluate.OUT")), col_types = NULL, 
 #                              col_names = NULL, 
 #                            left_justified = NULL, 
 #             read_only = NULL,  store_v_fmt = FALSE)
#OUT_UYKA1801 <- OUT1 %>% dplyr::select(EXCODE, TRNO, HWAMS, HWAMM, LAIXS, LAIXM, CWAMS, CWAMM)

#Gernam <- read_csv("data/ClonTRNO/UYKA1801.csv")
#DUYKA1801 <- left_join(Gernam, OUT_UYKA1801)

## from weather output file 
#OUT2 <- read_output((here::here("Weather.OUT")), col_types = NULL, 
 #                              col_names = NULL, 
 #                            left_justified = NULL, 
  #            read_only = NULL,  store_v_fmt = FALSE)
#OUTweath_UYKA1801 <- OUT2 %>% slice(1:366) %>% 
 #                mutate(TMAX = TMXD, TMIN = TMND, RAIN = PRED, 
 #                       PAR = PARD, WIND = WDSD) %>%
  #           dplyr::select(TMIN, TMAX, RAIN, SRAD, PAR, WIND)

#HUMID1 <- read_lines(here::here("UYKA1704.WTH"), skip = 565, n_max = 366)
#write_lines(HUMID1, (here::here("HUMIDUS.txt")))
#HUMIDEC <- read.table(here::here("HUMIDUS.txt"), header = FALSE, sep = "", dec = ".")
#HUMID2 <- HUMIDEC %>% mutate(TMAX = V4, TMIN = V3, RH2M = V6)%>% 
 #                      dplyr::select(TMAX, TMIN, RH2M)  
#OUTweath_UYKA1801 <- left_join(OUTweath_UYKA1801, HUMID2)

#Merge column
#DUYKA1801$TMIN <- mean(OUTweath_UYKA1801$TMIN, na.rm = TRUE)
#DUYKA1801$TMAX <- mean(OUTweath_UYKA1801$TMAX, na.rm = TRUE)
#DUYKA1801$SRAD <- mean(OUTweath_UYKA1801$SRAD, na.rm = TRUE)
#DUYKA1801$PAR <- mean(OUTweath_UYKA1801$PAR, na.rm = TRUE)
#DUYKA1801$RH2M <- mean(OUTweath_UYKA1801$RH2M, na.rm = TRUE)
#DUYKA1801$WIND <- mean(OUTweath_UYKA1801$WIND, na.rm = TRUE)
#DUYKA1801$RAIN <- sum(OUTweath_UYKA1801$RAIN)
#DUYKA1801$ELEV <- 634
#DUYKA1801$LAT <- 11.698
#DUYKA1801$LONG <- 7.704
```

```{r}
write_dssbatch("UYMO1701.CSX", trtno = 1:63)
run_dssat(suppress_output = TRUE)
OUT1 <- read_output((here::here("Evaluate.OUT")), col_types = NULL, 
                               col_names = NULL, 
                             left_justified = NULL, 
              read_only = NULL,  store_v_fmt = FALSE)
OUT_UYMO1701 <- OUT1 %>% dplyr::select(EXCODE, TRNO, HWAMS, HWAMM, LAIXS, LAIXM, CWAMS, CWAMM)

Gernam <- read_csv("data/ClonTRNO/UYMO1701.csv")
DUYMO1701 <- left_join(Gernam, OUT_UYMO1701)

## from weather output file 
OUT2 <- read_output((here::here("Weather.OUT")), col_types = NULL, 
                               col_names = NULL, 
                             left_justified = NULL, 
              read_only = NULL,  store_v_fmt = FALSE)
OUTweath_UYMO1701 <- OUT2 %>% slice(1:384) %>% 
                 mutate(TMAX = TMXD, TMIN = TMND, RAIN = PRED, 
                        PAR = PARD, WIND = WDSD) %>%
             dplyr::select(TMIN, TMAX, RAIN, SRAD, PAR, WIND)

HUMID1 <- read_lines(here::here("UYMO1704.WTH"), skip = 237, n_max = 384)
write_lines(HUMID1, (here::here("HUMIDUS.txt")))
HUMIDEC <- read.table(here::here("HUMIDUS.txt"), header = FALSE, sep = "", dec = ".")
HUMID2 <- HUMIDEC %>% mutate(TMAX = V4, TMIN = V3, RH2M = V6)%>% 
                       dplyr::select(TMAX, TMIN, RH2M)  
OUTweath_UYMO1701 <- left_join(OUTweath_UYMO1701, HUMID2)

#Merge column
DUYMO1701$TMIN <- mean(OUTweath_UYMO1701$TMIN, na.rm = TRUE)
DUYMO1701$TMAX <- mean(OUTweath_UYMO1701$TMAX, na.rm = TRUE)
DUYMO1701$SRAD <- mean(OUTweath_UYMO1701$SRAD, na.rm = TRUE)
DUYMO1701$PAR <- mean(OUTweath_UYMO1701$PAR, na.rm = TRUE)
DUYMO1701$RH2M <- mean(OUTweath_UYMO1701$RH2M, na.rm = TRUE)
DUYMO1701$WIND <- mean(OUTweath_UYMO1701$WIND, na.rm = TRUE)
DUYMO1701$RAIN <- sum(OUTweath_UYMO1701$RAIN)
DUYMO1701$ELEV <- 181
DUYMO1701$LAT <- 9.3097
DUYMO1701$LONG <- 5.0728
```

```{r}
write_dssbatch("UYMO1801.CSX", trtno = 1:67)
run_dssat(suppress_output = TRUE)
OUT1 <- read_output((here::here("Evaluate.OUT")), col_types = NULL, 
                               col_names = NULL, 
                             left_justified = NULL, 
              read_only = NULL,  store_v_fmt = FALSE)
OUT_UYMO1801 <- OUT1 %>% dplyr::select(EXCODE, TRNO, HWAMS, HWAMM, LAIXS, LAIXM, CWAMS, CWAMM)

Gernam <- read_csv("data/ClonTRNO/UYMO1801.csv")
DUYMO1801 <- left_join(Gernam, OUT_UYMO1801)

## from weather output file 
OUT2 <- read_output((here::here("Weather.OUT")), col_types = NULL, 
                               col_names = NULL, 
                             left_justified = NULL, 
              read_only = NULL,  store_v_fmt = FALSE)
OUTweath_UYMO1801 <- OUT2 %>% slice(1:366) %>% 
                 mutate(TMAX = TMXD, TMIN = TMND, RAIN = PRED, 
                        PAR = PARD, WIND = WDSD) %>%
             dplyr::select(TMIN, TMAX, RAIN, SRAD, PAR, WIND)

HUMID1 <- read_lines(here::here("UYMO1704.WTH"), skip = 534, n_max = 366)
write_lines(HUMID1, (here::here("HUMIDUS.txt")))
HUMIDEC <- read.table(here::here("HUMIDUS.txt"), header = FALSE, sep = "", dec = ".")
HUMID2 <- HUMIDEC %>% mutate(TMAX = V4, TMIN = V3, RH2M = V6)%>% 
                       dplyr::select(TMAX, TMIN, RH2M)  
OUTweath_UYMO1801 <- left_join(OUTweath_UYMO1801, HUMID2)

#Merge column
DUYMO1801$TMIN <- mean(OUTweath_UYMO1801$TMIN, na.rm = TRUE)
DUYMO1801$TMAX <- mean(OUTweath_UYMO1801$TMAX, na.rm = TRUE)
DUYMO1801$SRAD <- mean(OUTweath_UYMO1801$SRAD, na.rm = TRUE)
DUYMO1801$PAR <- mean(OUTweath_UYMO1801$PAR, na.rm = TRUE)
DUYMO1801$RH2M <- mean(OUTweath_UYMO1801$RH2M, na.rm = TRUE)
DUYMO1801$WIND <- mean(OUTweath_UYMO1801$WIND, na.rm = TRUE)
DUYMO1801$RAIN <- sum(OUTweath_UYMO1801$RAIN)
DUYMO1801$ELEV <- 181
DUYMO1801$LAT <- 9.3097
DUYMO1801$LONG <- 5.0728
```

```{r}
write_dssbatch("UYMO1901.CSX", trtno = 1:36)
run_dssat(suppress_output = TRUE)
OUT1 <- read_output((here::here("Evaluate.OUT")), col_types = NULL, 
                               col_names = NULL, 
                             left_justified = NULL, 
              read_only = NULL,  store_v_fmt = FALSE)
OUT_UYMO1901 <- OUT1 %>% dplyr::select(EXCODE, TRNO, HWAMS, HWAMM, LAIXS, LAIXM, CWAMS, CWAMM)

Gernam <- read_csv("data/ClonTRNO/UYMO1901.csv")
DUYMO1901 <- left_join(Gernam, OUT_UYMO1901)

## from weather output file 
OUT2 <- read_output((here::here("Weather.OUT")), col_types = NULL, 
                               col_names = NULL, 
                             left_justified = NULL, 
              read_only = NULL,  store_v_fmt = FALSE)
OUTweath_UYMO1901 <- OUT2 %>% slice(1:366) %>% 
                 mutate(TMAX = TMXD, TMIN = TMND, RAIN = PRED, 
                        PAR = PARD, WIND = WDSD) %>%
             dplyr::select(TMIN, TMAX, RAIN, SRAD, PAR, WIND)

HUMID1 <- read_lines(here::here("UYMO1704.WTH"), skip = 911, n_max = 366)
write_lines(HUMID1, (here::here("HUMIDUS.txt")))
HUMIDEC <- read.table(here::here("HUMIDUS.txt"), header = FALSE, sep = "", dec = ".")
HUMID2 <- HUMIDEC %>% mutate(TMAX = V4, TMIN = V3, RH2M = V6)%>% 
                       dplyr::select(TMAX, TMIN, RH2M)  
OUTweath_UYMO1901 <- left_join(OUTweath_UYMO1901, HUMID2)

#Merge column
DUYMO1901$TMIN <- mean(OUTweath_UYMO1901$TMIN, na.rm = TRUE)
DUYMO1901$TMAX <- mean(OUTweath_UYMO1901$TMAX, na.rm = TRUE)
DUYMO1901$SRAD <- mean(OUTweath_UYMO1901$SRAD, na.rm = TRUE)
DUYMO1901$PAR <- mean(OUTweath_UYMO1901$PAR, na.rm = TRUE)
DUYMO1901$RH2M <- mean(OUTweath_UYMO1901$RH2M, na.rm = TRUE)
DUYMO1901$WIND <- mean(OUTweath_UYMO1901$WIND, na.rm = TRUE)
DUYMO1901$RAIN <- sum(OUTweath_UYMO1901$RAIN)
DUYMO1901$ELEV <- 181
DUYMO1901$LAT <- 9.3097
DUYMO1901$LONG <- 5.0728
```

```{r}
write_dssbatch("UYON1801.CSX", trtno = 1:67)
run_dssat(suppress_output = TRUE)
OUT1 <- read_output((here::here("Evaluate.OUT")), col_types = NULL, 
                              col_names = NULL, 
                            left_justified = NULL, 
              read_only = NULL,  store_v_fmt = FALSE)
OUT_UYON1801 <- OUT1 %>% dplyr::select(EXCODE, TRNO, HWAMS, HWAMM, LAIXS, LAIXM, CWAMS, CWAMM)

Gernam <- read_csv("data/ClonTRNO/UYON1801.csv")
DUYON1801 <- left_join(Gernam, OUT_UYON1801)

# from weather output file 
OUT2 <- read_output((here::here("Weather.OUT")), col_types = NULL, 
                               col_names = NULL, 
                             left_justified = NULL, 
              read_only = NULL,  store_v_fmt = FALSE)
OUTweath_UYON1801 <- OUT2 %>% slice(1:366) %>% 
                 mutate(TMAX = TMXD, TMIN = TMND, RAIN = PRED, 
                        PAR = PARD, WIND = WDSD) %>%
             dplyr::select(TMIN, TMAX, RAIN, SRAD, PAR, WIND)

HUMID1 <- read_lines(here::here("UYON1704.WTH"), skip = 486, n_max = 366)
write_lines(HUMID1, (here::here("HUMIDUS.txt")))
HUMIDEC <- read.table(here::here("HUMIDUS.txt"), header = FALSE, sep = "", dec = ".")
HUMID2 <- HUMIDEC %>% mutate(TMAX = V4, TMIN = V3, RH2M = V6)%>% 
                       dplyr::select(TMAX, TMIN, RH2M)  
OUTweath_UYON1801 <- left_join(OUTweath_UYON1801, HUMID2)

#Merge column
DUYON1801$TMIN <- mean(OUTweath_UYON1801$TMIN, na.rm = TRUE)
DUYON1801$TMAX <- mean(OUTweath_UYON1801$TMAX, na.rm = TRUE)
DUYON1801$SRAD <- mean(OUTweath_UYON1801$SRAD, na.rm = TRUE)
DUYON1801$PAR <- mean(OUTweath_UYON1801$PAR, na.rm = TRUE)
DUYON1801$RH2M <- mean(OUTweath_UYON1801$RH2M, na.rm = TRUE)
DUYON1801$WIND <- mean(OUTweath_UYON1801$WIND, na.rm = TRUE)
DUYON1801$RAIN <- sum(OUTweath_UYON1801$RAIN)
DUYON1801$ELEV <- 27
DUYON1801$LAT <- 4.7949
DUYON1801$LONG <- 7.1691
```

Not run
```{r}
#write_dssbatch("UYOT1801.CSX", trtno = 1:55)
#run_dssat(suppress_output = TRUE)
#OUT1 <- read_output((here::here("Evaluate.OUT")), col_types = NULL, 
 #                              col_names = NULL, 
 #                            left_justified = NULL, 
  #            read_only = NULL,  store_v_fmt = FALSE)
#OUT_UYOT1801 <- OUT1 %>% dplyr::select(EXCODE, TRNO, HWAMS, HWAMM, LAIXS, LAIXM, CWAMS, CWAMM)

#Gernam <- read_csv("data/ClonTRNO/UYOT1801.csv")
#DUYOT1801 <- left_join(Gernam, OUT_UYOT1801)

# from weather output file 
#OUT2 <- read_output((here::here("Weather.OUT")), col_types = NULL, 
#                               col_names = NULL, 
 #                            left_justified = NULL, 
  #            read_only = NULL,  store_v_fmt = FALSE)
#OUTweath_UYOT1801 <- OUT2 %>% slice(1:366) %>% 
  #               mutate(TMAX = TMXD, TMIN = TMND, RAIN = PRED, 
  #                      PAR = PARD, WIND = WDSD) %>%
   #          dplyr::select(TMIN, TMAX, RAIN, SRAD, PAR, WIND)

#HUMID1 <- read_lines(here::here("UYOT1704.WTH"), skip = 567, n_max = 366)
#write_lines(HUMID1, (here::here("HUMIDUS.txt")))
#HUMIDEC <- read.table(here::here("HUMIDUS.txt"), header = FALSE, sep = "", dec = ".")
#HUMID2 <- HUMIDEC %>% mutate(TMAX = V4, TMIN = V3, RH2M = V6)%>% 
#                       dplyr::select(TMAX, TMIN, RH2M)  
#OUTweath_UYOT1801 <- left_join(OUTweath_UYOT1801, HUMID2)

#Merge column
#DUYOT1801$TMIN <- mean(OUTweath_UYOT1801$TMIN, na.rm = TRUE)
#DUYOT1801$TMAX <- mean(OUTweath_UYOT1801$TMAX, na.rm = TRUE)
#DUYOT1801$SRAD <- mean(OUTweath_UYOT1801$SRAD, na.rm = TRUE)
#DUYOT1801$PAR <- mean(OUTweath_UYOT1801$PAR, na.rm = TRUE)
#DUYOT1801$RH2M <- mean(OUTweath_UYOT1801$RH2M, na.rm = TRUE)
#DUYOT1801$WIND <- mean(OUTweath_UYOT1801$WIND, na.rm = TRUE)
#DUYOT1801$RAIN <- sum(OUTweath_UYOT1801$RAIN)
#DUYOT1801$ELEV <- 139
#DUYOT1801$LAT <- 7.1528
#DUYOT1801$LONG <- 8.2857
```


```{r}
write_dssbatch("UYUB1901.CSX", trtno = 1:67)
run_dssat(suppress_output = TRUE)
OUT1 <- read_output((here::here("Evaluate.OUT")), col_types = NULL, 
                               col_names = NULL, 
                             left_justified = NULL, 
              read_only = NULL,  store_v_fmt = FALSE)
OUT_UYUB1901 <- OUT1 %>% dplyr::select(EXCODE, TRNO, HWAMS, HWAMM, LAIXS, LAIXM, CWAMS, CWAMM)

Gernam <- read_csv("data/ClonTRNO/UYUB1901.csv")
DUYUB1901 <- left_join(Gernam, OUT_UYUB1901)

## from weather output file 
OUT2 <- read_output((here::here("Weather.OUT")), col_types = NULL, 
                               col_names = NULL, 
                             left_justified = NULL, 
              read_only = NULL,  store_v_fmt = FALSE)
OUTweath_UYUB1901 <- OUT2 %>% slice(1:370) %>% 
                 mutate(TMAX = TMXD, TMIN = TMND, RAIN = PRED, 
                        PAR = PARD, WIND = WDSD) %>%
             dplyr::select(TMIN, TMAX, RAIN, SRAD, PAR, WIND)

HUMID1 <- read_lines(here::here("UYUB1704.WTH"), skip = 885, n_max = 370)
write_lines(HUMID1, (here::here("HUMIDUS.txt")))
HUMIDEC <- read.table(here::here("HUMIDUS.txt"), header = FALSE, sep = "", dec = ".")
HUMID2 <- HUMIDEC %>% mutate(TMAX = V4, TMIN = V3, RH2M = V6)%>% 
                       dplyr::select(TMAX, TMIN, RH2M)  
OUTweath_UYUB1901 <- left_join(OUTweath_UYUB1901, HUMID2)

#Merge column
DUYUB1901$TMIN <- mean(OUTweath_UYUB1901$TMIN, na.rm = TRUE)
DUYUB1901$TMAX <- mean(OUTweath_UYUB1901$TMAX, na.rm = TRUE)
DUYUB1901$SRAD <- mean(OUTweath_UYUB1901$SRAD, na.rm = TRUE)
DUYUB1901$PAR <- mean(OUTweath_UYUB1901$PAR, na.rm = TRUE)
DUYUB1901$RH2M <- mean(OUTweath_UYUB1901$RH2M, na.rm = TRUE)
DUYUB1901$WIND <- mean(OUTweath_UYUB1901$WIND, na.rm = TRUE)
DUYUB1901$RAIN <- sum(OUTweath_UYUB1901$RAIN)
DUYUB1901$ELEV <- 153.83
DUYUB1901$LAT <- 6.6702
DUYUB1901$LONG <- 6.3857
```

```{r}
write_dssbatch("UYUM1801.CSX", trtno = 1:67)
run_dssat(suppress_output = TRUE)
OUT1 <- read_output((here::here("Evaluate.OUT")), col_types = NULL, 
                               col_names = NULL, 
                             left_justified = NULL, 
              read_only = NULL,  store_v_fmt = FALSE)
OUT_UYUM1801 <- OUT1 %>% dplyr::select(EXCODE, TRNO, HWAMS, HWAMM, LAIXS, LAIXM, CWAMS, CWAMM)

Gernam <- read_csv("data/ClonTRNO/UYUM1801.csv")
DUYUM1801 <- left_join(Gernam, OUT_UYUM1801)

## from weather output file 
OUT2 <- read_output((here::here("Weather.OUT")), col_types = NULL, 
                               col_names = NULL, 
                             left_justified = NULL, 
              read_only = NULL,  store_v_fmt = FALSE)
OUTweath_UYUM1801 <- OUT2 %>% slice(1:366) %>% 
                 mutate(TMAX = TMXD, TMIN = TMND, RAIN = PRED, 
                        PAR = PARD, WIND = WDSD) %>%
             dplyr::select(TMIN, TMAX, RAIN, SRAD, PAR, WIND)

HUMID1 <- read_lines(here::here("UYUM1704.WTH"), skip = 577, n_max = 366)
write_lines(HUMID1, (here::here("HUMIDUS.txt")))
HUMIDEC <- read.table(here::here("HUMIDUS.txt"), header = FALSE, sep = "", dec = ".")
HUMID2 <- HUMIDEC %>% mutate(TMAX = V4, TMIN = V3, RH2M = V6)%>% 
                       dplyr::select(TMAX, TMIN, RH2M)  
OUTweath_UYUM1801 <- left_join(OUTweath_UYUM1801, HUMID2)

#Merge column
DUYUM1801$TMIN <- mean(OUTweath_UYUM1801$TMIN, na.rm = TRUE)
DUYUM1801$TMAX <- mean(OUTweath_UYUM1801$TMAX, na.rm = TRUE)
DUYUM1801$SRAD <- mean(OUTweath_UYUM1801$SRAD, na.rm = TRUE)
DUYUM1801$PAR <- mean(OUTweath_UYUM1801$PAR, na.rm = TRUE)
DUYUM1801$RH2M <- mean(OUTweath_UYUM1801$RH2M, na.rm = TRUE)
DUYUM1801$WIND <- mean(OUTweath_UYUM1801$WIND, na.rm = TRUE)
DUYUM1801$RAIN <- sum(OUTweath_UYUM1801$RAIN)
DUYUM1801$ELEV <- 93
DUYUM1801$LAT <- 5.4732
DUYUM1801$LONG <- 7.5512
```

Not run
```{r}
#write_dssbatch("UYZA1901.CSX", trtno = 1:4)
#run_dssat(suppress_output = TRUE)
#OUT1 <- read_output((here::here("Evaluate.OUT")), col_types = NULL, 
 #                              col_names = NULL, 
 #                            left_justified = NULL, 
 #            read_only = NULL,  store_v_fmt = FALSE)
#OUT_UYZA1901 <- OUT1 %>% dplyr::select(EXCODE, TRNO, HWAMS, HWAMM, LAIXS, LAIXM, CWAMS, CWAMM)

#Gernam <- read_csv("data/ClonTRNO/UYZA1901.csv")
#DUYZA1901 <- left_join(Gernam, OUT_UYZA1901)

## from weather output file 
#OUT2 <- read_output((here::here("Weather.OUT")), col_types = NULL, 
#                               col_names = NULL, 
 #                            left_justified = NULL, 
  #            read_only = NULL,  store_v_fmt = FALSE)
#OUTweath_UYZA1901 <- OUT2 %>% slice(1:408) %>% 
#                 mutate(TMAX = TMXD, TMIN = TMND, RAIN = PRED, 
 #                       PAR = PARD, WIND = WDSD) %>%
  #           dplyr::select(TMIN, TMAX, RAIN, SRAD, PAR, WIND)

#HUMID1 <- read_lines(here::here("UYZA1704.WTH"), skip = 885, n_max = 370)
#write_lines(HUMID1, (here::here("HUMIDUS.txt")))
#HUMIDEC <- read.table(here::here("HUMIDUS.txt"), header = FALSE, sep = "", dec = ".")
#HUMID2 <- HUMIDEC %>% mutate(TMAX = V4, TMIN = V3, RH2M = V6)%>% 
 #                      dplyr::select(TMAX, TMIN, RH2M)  
#OUTweath_UYZA1901 <- left_join(OUTweath_UYZA1901, HUMID2)

#Merge column
#DUYZA1901$TMIN <- mean(OUTweath_UYZA1901$TMIN, na.rm = TRUE)
#DUYZA1901$TMAX <- mean(OUTweath_UYZA1901$TMAX, na.rm = TRUE)
#DUYZA1901$SRAD <- mean(OUTweath_UYZA1901$SRAD, na.rm = TRUE)
#DUYZA1901$PAR <- mean(OUTweath_UYZA1901$PAR, na.rm = TRUE)
#DUYZA1901$RH2M <- mean(OUTweath_UYZA1901$RH2M, na.rm = TRUE)
#DUYZA1901$WIND <- mean(OUTweath_UYZA1901$WIND, na.rm = TRUE)
#DUYZA1901$RAIN <- sum(OUTweath_UYZA1901$RAIN)
#DUYZA1901$ELEV <- 647
#DUYZA1901$LAT <- 11.0506
#DUYZA1901$LONG <- 7.7315
```


```{r}
#get all the evaluate Output
GLUEVAL2 <- bind_rows(Abuja19 = DUYAB1901, Ago17 = DUYAG1701, Ago18 = DUYAG1801, Ago19 = DUYAG1901, Ibadan17 = DUYIB1701, Ibadan18 = DUYIB1801, Ibadan19 = DUYIB1901, Ikenne17 = DUYIK1701, Ikenne18 = DUYIK1801, Ikenne19 = DUYIK1901, Mokwa17 = DUYMO1701, Mokwa18 = DUYMO1801, Mokwa19 = DUYMO1901, Onne18 = DUYON1801, Ubiaja19 = DUYUB1901, Umudike18 = DUYUM1801, .id = "source") %>%
       mutate(HWAMMS = HWAMM - HWAMS,
              HWAMMSsq = (HWAMM - HWAMS)^2) #ADD Zaria19 = DUYZA1901 later #for observed-simulated Abuja19 = DUYAB1901, Ago17 = DUYAG1701, Ago18 = DUYAG1801, Ago19 = DUYAG1901, Ibadan17 = DUYIB1701, Ibadan18 = DUYIB1801, Ibadan19 = DUYIB1901, Ikenne17 = DUYIK1701, Ikenne18 = DUYIK1801, Ikenne19 = DUYIK1901, Kano18 = DUYKA1801, Mokwa17 = DUYMO1701, Mokwa18 = DUYMO1801, Mokwa19 = DUYMO1901, Onne18 = DUYON1801, Otobio18 = DUYOT1801, Ubiaja19 = DUYUB1901, Umudike18 = DUYUM1801, Zaria19 = DUYZA1901, .id = "source")
#colnames()
colnames(GLUEVAL2)
GLUEVAL2$year <- as.numeric(paste0("20", str_extract(GLUEVAL2$source, "\\d{2}+")))
write.csv(GLUEVAL2, "data/GLUEHWAM_VALana.csv", quote = F, row.names = F)# EVALana.csv
```


##create location
```{r}
library(data.table)
GLUEYIELD <- read.csv("data/GLUEHWAM_VALana.csv")
GLUEYIELD$Location <- GLUEYIELD$EXCODE
GLUEYIELD$Location[grep(pattern = "^UYAB", x = GLUEYIELD$EXCODE)] <- "ABUJA"
GLUEYIELD$Location[grep(pattern = "^UYAG", x = GLUEYIELD$EXCODE)] <- "AGO"
GLUEYIELD$Location[grep(pattern = "^UYIB", x = GLUEYIELD$EXCODE)] <- "IBADAN"
GLUEYIELD$Location[grep(pattern = "^UYIK", x = GLUEYIELD$EXCODE)] <- "IKENNE"
#GLUEYIELD$Location[grep(pattern = "^UYKA", x = GLUEYIELD$EXCODE)] <- "KANO"
GLUEYIELD$Location[grep(pattern = "^UYMO", x = GLUEYIELD$EXCODE)] <- "MOKWA"
GLUEYIELD$Location[grep(pattern = "^UYON", x = GLUEYIELD$EXCODE)] <- "ONNE"
#GLUEYIELD$Location[grep(pattern = "^UYOT", x = GLUEYIELD$EXCODE)] <- "OTOBI"
GLUEYIELD$Location[grep(pattern = "^UYUB", x = GLUEYIELD$EXCODE)] <- "UBIAJA"
GLUEYIELD$Location[grep(pattern = "^UYUM", x = GLUEYIELD$EXCODE)] <- "UMUDIKE"
#GLUEYIELD$Location[grep(pattern = "^UYZA", x = GLUEYIELD$EXCODE)] <- "ZARIA"

GLUEYIELD$Year <- GLUEYIELD$EXCODE
#GLUEYIELD$Year[grep(pattern = "*2001CS", x = GLUEYIELD$EXCODE)] <- "2020"
GLUEYIELD$Year[grep(pattern = "*1901CS", x = GLUEYIELD$EXCODE)] <- "2019"
GLUEYIELD$Year[grep(pattern = "*1801CS", x = GLUEYIELD$EXCODE)] <- "2018"
GLUEYIELD$Year[grep(pattern = "*1701CS", x = GLUEYIELD$EXCODE)] <- "2017"
```



####For Prcom
```{r}
#create a new column = environment
Env <- unique(GLUEVAL2$source) %>% .[order(.)]

HMMM <- GLUEVAL2 %>% filter(source == Env[1]) %>% 
            dplyr::select(Clone, HWAMMS) %>% 
             mutate(Ago18 = HWAMMS / 1000, 
                    Ago18 = as.numeric(Ago18), .keep = "unused")
for(i in Env[-1]) {
      EVAL2P <- GLUEVAL2 %>% 
          filter(source == i) %>% 
             dplyr::select(Clone, HWAMMS) %>% 
             mutate(HWAMMS = HWAMMS / 1000,
                    HWAMMS = as.numeric(HWAMMS))
      colnames(EVAL2P)[2] <- i
      HMMM <- HMMM %>% left_join(EVAL2P, by = "Clone")
}
```

```{r}
#Calculate the mean of 'observed-simulated
HMMM$Ibadan17[is.na(HMMM$Ibadan17)] <- mean(HMMM$Ibadan17, na.rm = TRUE)
HMMM$Ibadan18[is.na(HMMM$Ibadan18)] <- mean(HMMM$Ibadan18, na.rm = TRUE)
HMMM$Ibadan19[is.na(HMMM$Ibadan19)] <- mean(HMMM$Ibadan19, na.rm = TRUE)
HMMM$Ikenne17[is.na(HMMM$Ikenne17)] <- mean(HMMM$Ikenne17, na.rm = TRUE)
HMMM$Ikenne18[is.na(HMMM$Ikenne18)] <- mean(HMMM$Ikenne18, na.rm = TRUE)
HMMM$Mokwa17[is.na(HMMM$Mokwa17)] <- mean(HMMM$Mokwa17, na.rm = TRUE)
PRdata <- HMMM %>%
     remove_rownames() %>%
     column_to_rownames(var = 'Clone')# %>%
      #mutate(Abuja19 = as.numeric(Abuja19),
          #   Ago17 = as.numeric(Ago17),
            # Ago18 = as.numeric(Ago18),
            # Ago19 = as.numeric(Ago19),
            # Ibadan17 = suppressWarnings(as.numeric(Ibadan17)),
            # Ibadan18 = as.numeric(Ibadan18),
           # Ibadan19 = suppressWarnings(as.numeric(Ibadan19)),
            #Ikenne17 = suppressWarnings(as.numeric(Ikenne17)),
            #Ikenne18 = suppressWarnings(as.numeric(Ikenne18)),
           # Ikenne19 = suppressWarnings(as.numeric(Ikenne19)),
           # Kano18 = as.numeric(Kano18),
           # Mokwa17 = suppressWarnings(as.numeric(Mokwa17)),
           # Mokwa18 = as.numeric(Mokwa18),
           # Mokwa19 = as.numeric(Mokwa19),
          #  Onne18 = as.numeric(Onne18),
            # Otobio18 = as.numeric(Otobio18),
            # Ubiaja19 = as.numeric(Ubiaja19),
            # Umudike18 = as.numeric(Umudike18),
             #Zaria19 = as.numeric(Zaria19))
```
## check weather parameter variation accross cassava cycle time: 4 main cycle time for cassava
```{r}
OUTweath_UYAB1901C <- OUTweath_UYAB1901 %>% mutate(DayAfPlanting = rownames(OUTweath_UYAB1901),
                                               ENV = "Abuja19")
OUTweath_UYAG1701C <- OUTweath_UYAG1701 %>% mutate(DayAfPlanting = rownames(OUTweath_UYAG1701),
                                                   ENV = "Ago17")
OUTweath_UYAG1801C <- OUTweath_UYAG1801 %>% mutate(DayAfPlanting = rownames(OUTweath_UYAG1801),
                                                   ENV = "Ago18")
OUTweath_UYAG1901C <- OUTweath_UYAG1901 %>% mutate(DayAfPlanting = rownames(OUTweath_UYAG1901),
                                                   ENV = "Ago19")
OUTweath_UYIB1701C <- OUTweath_UYIB1701 %>% mutate(DayAfPlanting = rownames(OUTweath_UYIB1701),
                                                   ENV = "Ibadan17")
OUTweath_UYIB1801C <- OUTweath_UYIB1801 %>% mutate(DayAfPlanting = rownames(OUTweath_UYIB1801),
                                                   ENV = "Ibadan18")
OUTweath_UYIB1901C <- OUTweath_UYIB1901 %>% mutate(DayAfPlanting = rownames(OUTweath_UYIB1901),
                                                   ENV = "Ibadan19")
OUTweath_UYIK1701C <- OUTweath_UYIK1701 %>% mutate(DayAfPlanting = rownames(OUTweath_UYIK1701),
                                                   ENV = "Ikenne17")
OUTweath_UYIK1801C <- OUTweath_UYIK1801 %>% mutate(DayAfPlanting = rownames(OUTweath_UYIK1801),
                                                   ENV = "Ikenne18")
OUTweath_UYIK1901C <- OUTweath_UYIK1901 %>% mutate(DayAfPlanting = rownames(OUTweath_UYIK1901),
                                                   ENV = "Ikenne19")
#OUTweath_UYKA1801C <- OUTweath_UYKA1801 %>% mutate(DayAfPlanting = rownames(OUTweath_UYKA1801),
  #                                                 ENV = "Kano18")
OUTweath_UYMO1701C <- OUTweath_UYMO1701 %>% mutate(DayAfPlanting = rownames(OUTweath_UYMO1701),
                                                   ENV = "Mokwa17")
OUTweath_UYMO1801C <- OUTweath_UYMO1801 %>% mutate(DayAfPlanting = rownames(OUTweath_UYMO1801),
                                                   ENV = "Mokwa18")
OUTweath_UYMO1901C <- OUTweath_UYMO1901 %>% mutate(DayAfPlanting = rownames(OUTweath_UYMO1901),
                                                   ENV = "Mokwa19")
OUTweath_UYON1801C <- OUTweath_UYON1801 %>% mutate(DayAfPlanting = rownames(OUTweath_UYON1801),
                                                   ENV = "Onne18")
#OUTweath_UYOT1801C <- OUTweath_UYOT1801 %>% mutate(DayAfPlanting = rownames(OUTweath_UYOT1801),
  #                                                 ENV = "Otobio18")
OUTweath_UYUB1901C <- OUTweath_UYUB1901 %>% mutate(DayAfPlanting = rownames(OUTweath_UYUB1901),
                                                   ENV = "Ubiaja19")
OUTweath_UYUM1801C <- OUTweath_UYUM1801 %>% mutate(DayAfPlanting = rownames(OUTweath_UYUM1801),
                                                   ENV = "Umudike18")
#OUTweath_UYZA1901C <- OUTweath_UYZA1901 %>% mutate(DayAfPlanting = rownames(OUTweath_UYZA1901),
  #                                                 ENV = "Zaria19")
weather_cycle1 <- bind_rows(OUTweath_UYAB1901C, OUTweath_UYAG1701C, OUTweath_UYAG1801C, OUTweath_UYAG1901C, OUTweath_UYIB1701C, OUTweath_UYIB1801C, OUTweath_UYIB1901C, OUTweath_UYIK1701C, OUTweath_UYIK1801C, OUTweath_UYIK1901C,  OUTweath_UYMO1701C, OUTweath_UYMO1801C,OUTweath_UYMO1901C, OUTweath_UYON1801C,  OUTweath_UYUB1901C, OUTweath_UYUM1801C)#OUTweath_UYKA1801C,OUTweath_UYOT1801C,

weather_cycle <- weather_cycle1 %>%
      mutate(DayAfPlanting = as.integer(DayAfPlanting),
         MonthAfPlanting = ifelse(DayAfPlanting <= 90,
                                  yes = 3,
                                  no =  ifelse(DayAfPlanting <= 180,
                                               yes = 6,
                                               no = ifelse(DayAfPlanting <= 270,
                                                           yes = 9,
                                                           no = 12)))) %>%
           group_by(ENV, MonthAfPlanting) %>%
             summarise(TMIN = mean(TMIN, na.rm=TRUE), 
                       TMAX = mean(TMAX, na.rm=TRUE),
                       SRAD = mean(SRAD, na.rm=TRUE), 
                       RHUM = mean(RH2M, na.rm=TRUE), 
                       RAIN = sum(RAIN)) %>%
             mutate(TMIN1 = case_when(MonthAfPlanting == 3 ~ TMIN),
                    TMIN2 = case_when(MonthAfPlanting == 6 ~ TMIN),
                    TMIN3 = case_when(MonthAfPlanting == 9 ~ TMIN),
                    TMIN4 = case_when(MonthAfPlanting == 12 ~ TMIN),
                    TMAX1 = case_when(MonthAfPlanting == 3 ~ TMAX),
                    TMAX2 = case_when(MonthAfPlanting == 6 ~ TMAX),
                    TMAX3 = case_when(MonthAfPlanting == 9 ~ TMAX),
                    TMAX4 = case_when(MonthAfPlanting == 12 ~ TMAX),
                    SRAD1 = case_when(MonthAfPlanting == 3 ~ SRAD),
                    SRAD2 = case_when(MonthAfPlanting == 6 ~ SRAD),
                    SRAD3 = case_when(MonthAfPlanting == 9 ~ SRAD),
                    SRAD4 = case_when(MonthAfPlanting == 12 ~ SRAD),
                    RHUM1 = case_when(MonthAfPlanting == 3 ~ RHUM),
                    RHUM2 = case_when(MonthAfPlanting == 6 ~ RHUM),
                    RHUM3 = case_when(MonthAfPlanting == 9 ~ RHUM),
                    RHUM4 = case_when(MonthAfPlanting == 12 ~ RHUM),
                    RAIN1 = case_when(MonthAfPlanting == 3 ~ RAIN),
                    RAIN2 = case_when(MonthAfPlanting == 6 ~ RAIN),
                    RAIN3 = case_when(MonthAfPlanting == 9 ~ RAIN),
                    RAIN4 = case_when(MonthAfPlanting == 12 ~ RAIN)) %>% 
                dplyr::select(ENV, TMIN1, TMIN2, TMIN3, TMIN4, TMAX1, TMAX2, TMAX3, TMAX4, 
                       SRAD1, SRAD2, SRAD3, SRAD4, RHUM1, RHUM2, RHUM3, RHUM4,
                       RAIN1, RAIN2, RAIN3, RAIN4)
                      

weather_cycleT1 <- weather_cycle %>% filter(!is.na(TMIN1)) %>%
                                  dplyr::select(ENV, TMIN1, TMAX1, SRAD1, RHUM1, RAIN1)
weather_cycleT2 <- weather_cycle %>% filter(!is.na(TMIN2)) %>%
                                  dplyr::select(ENV, TMIN2, TMAX2, SRAD2, RHUM2, RAIN2)
weather_cycleT3 <- weather_cycle %>% filter(!is.na(TMIN3)) %>%
                                  dplyr::select(ENV, TMIN3, TMAX3, SRAD3, RHUM3, RAIN3)
weather_cycleT4 <- weather_cycle %>% filter(!is.na(TMIN4)) %>%
                                  dplyr::select(ENV, TMIN4, TMAX4, SRAD4, RHUM4, RAIN4)
 
weather_cycleT5 <- left_join(weather_cycleT1, weather_cycleT2)
weather_cycleT6 <- left_join(weather_cycleT5, weather_cycleT3)
weather_cycleT <- left_join(weather_cycleT6, weather_cycleT4)
write.csv(weather_cycleT, "data/weather_cycle.csv", quote = F, row.names = F)
```

```{r}
OUTweath_UYAB1901_6 <- OUTweath_UYAB1901 %>% slice(1:180)
OUTweath_UYAB1901_9 <- OUTweath_UYAB1901 %>% slice(181:270)
OUTweath_UYAB1901_12 <- OUTweath_UYAB1901 %>% slice(270:406)
#Merge column
DUYAB1901$TMIN_6 <- mean(OUTweath_UYAB1901_6$TMIN, na.rm = TRUE)
DUYAB1901$TMIN_9 <- mean(OUTweath_UYAB1901_9$TMIN, na.rm = TRUE)
DUYAB1901$TMIN_12 <- mean(OUTweath_UYAB1901_12$TMIN, na.rm = TRUE)

DUYAB1901$TMAX_6 <- mean(OUTweath_UYAB1901_6$TMAX, na.rm = TRUE)
DUYAB1901$TMAX_9 <- mean(OUTweath_UYAB1901_9$TMAX, na.rm = TRUE)
DUYAB1901$TMAX_12 <- mean(OUTweath_UYAB1901_12$TMAX, na.rm = TRUE)

DUYAB1901$SRAD_6 <- mean(OUTweath_UYAB1901_6$SRAD, na.rm = TRUE)
DUYAB1901$SRAD_9 <- mean(OUTweath_UYAB1901_9$SRAD, na.rm = TRUE)
DUYAB1901$SRAD_12 <- mean(OUTweath_UYAB1901_12$SRAD, na.rm = TRUE)

DUYAB1901$PAR_6 <- mean(OUTweath_UYAB1901_6$PAR, na.rm = TRUE)
DUYAB1901$PAR_9 <- mean(OUTweath_UYAB1901_9$PAR, na.rm = TRUE)
DUYAB1901$PAR_12 <- mean(OUTweath_UYAB1901_12$PAR, na.rm = TRUE)

DUYAB1901$RH2M_6 <- mean(OUTweath_UYAB1901_6$RH2M, na.rm = TRUE)
DUYAB1901$RH2M_9 <- mean(OUTweath_UYAB1901_9$RH2M, na.rm = TRUE)
DUYAB1901$RH2M_12 <- mean(OUTweath_UYAB1901_12$RH2M, na.rm = TRUE)

DUYAB1901$WIND_6 <- mean(OUTweath_UYAB1901_6$WIND, na.rm = TRUE)
DUYAB1901$WIND_9 <- mean(OUTweath_UYAB1901_9$WIND, na.rm = TRUE)
DUYAB1901$WIND_12 <- mean(OUTweath_UYAB1901_12$WIND, na.rm = TRUE)

DUYAB1901$RAIN_6 <- sum(OUTweath_UYAB1901_6$RAIN)
DUYAB1901$RAIN_9 <- sum(OUTweath_UYAB1901_9$RAIN)
DUYAB1901$RAIN_12 <- sum(OUTweath_UYAB1901_12$RAIN)
```

```{r}
OUTweath_UYAG1701_6 <- OUTweath_UYAG1701 %>% slice(1:180)
OUTweath_UYAG1701_9 <- OUTweath_UYAG1701 %>% slice(181:270)
OUTweath_UYAG1701_12 <- OUTweath_UYAG1701 %>% slice(270:317)
#Merge column
DUYAG1701$TMIN_6 <- mean(OUTweath_UYAG1701_6$TMIN, na.rm = TRUE)
DUYAG1701$TMIN_9 <- mean(OUTweath_UYAG1701_9$TMIN, na.rm = TRUE)
DUYAG1701$TMIN_12 <- mean(OUTweath_UYAG1701_12$TMIN, na.rm = TRUE)

DUYAG1701$TMAX_6 <- mean(OUTweath_UYAG1701_6$TMAX, na.rm = TRUE)
DUYAG1701$TMAX_9 <- mean(OUTweath_UYAG1701_9$TMAX, na.rm = TRUE)
DUYAG1701$TMAX_12 <- mean(OUTweath_UYAG1701_12$TMAX, na.rm = TRUE)

DUYAG1701$SRAD_6 <- mean(OUTweath_UYAG1701_6$SRAD, na.rm = TRUE)
DUYAG1701$SRAD_9 <- mean(OUTweath_UYAG1701_9$SRAD, na.rm = TRUE)
DUYAG1701$SRAD_12 <- mean(OUTweath_UYAG1701_12$SRAD, na.rm = TRUE)

DUYAG1701$PAR_6 <- mean(OUTweath_UYAG1701_6$PAR, na.rm = TRUE)
DUYAG1701$PAR_9 <- mean(OUTweath_UYAG1701_9$PAR, na.rm = TRUE)
DUYAG1701$PAR_12 <- mean(OUTweath_UYAG1701_12$PAR, na.rm = TRUE)

DUYAG1701$RH2M_6 <- mean(OUTweath_UYAG1701_6$RH2M, na.rm = TRUE)
DUYAG1701$RH2M_9 <- mean(OUTweath_UYAG1701_9$RH2M, na.rm = TRUE)
DUYAG1701$RH2M_12 <- mean(OUTweath_UYAG1701_12$RH2M, na.rm = TRUE)

DUYAG1701$WIND_6 <- mean(OUTweath_UYAG1701_6$WIND, na.rm = TRUE)
DUYAG1701$WIND_9 <- mean(OUTweath_UYAG1701_9$WIND, na.rm = TRUE)
DUYAG1701$WIND_12 <- mean(OUTweath_UYAG1701_12$WIND, na.rm = TRUE)

DUYAG1701$RAIN_6 <- sum(OUTweath_UYAG1701_6$RAIN)
DUYAG1701$RAIN_9 <- sum(OUTweath_UYAG1701_9$RAIN)
DUYAG1701$RAIN_12 <- sum(OUTweath_UYAG1701_12$RAIN)
```

```{r}
OUTweath_UYAG1801_6 <- OUTweath_UYAG1801 %>% slice(1:180)
OUTweath_UYAG1801_9 <- OUTweath_UYAG1801 %>% slice(181:270)
OUTweath_UYAG1801_12 <- OUTweath_UYAG1801 %>% slice(210:366)
#Merge column
DUYAG1801$TMIN_6 <- mean(OUTweath_UYAG1801_6$TMIN, na.rm = TRUE)
DUYAG1801$TMIN_9 <- mean(OUTweath_UYAG1801_9$TMIN, na.rm = TRUE)
DUYAG1801$TMIN_12 <- mean(OUTweath_UYAG1801_12$TMIN, na.rm = TRUE)

DUYAG1801$TMAX_6 <- mean(OUTweath_UYAG1801_6$TMAX, na.rm = TRUE)
DUYAG1801$TMAX_9 <- mean(OUTweath_UYAG1801_9$TMAX, na.rm = TRUE)
DUYAG1801$TMAX_12 <- mean(OUTweath_UYAG1801_12$TMAX, na.rm = TRUE)

DUYAG1801$SRAD_6 <- mean(OUTweath_UYAG1801_6$SRAD, na.rm = TRUE)
DUYAG1801$SRAD_9 <- mean(OUTweath_UYAG1801_9$SRAD, na.rm = TRUE)
DUYAG1801$SRAD_12 <- mean(OUTweath_UYAG1801_12$SRAD, na.rm = TRUE)

DUYAG1801$PAR_6 <- mean(OUTweath_UYAG1801_6$PAR, na.rm = TRUE)
DUYAG1801$PAR_9 <- mean(OUTweath_UYAG1801_9$PAR, na.rm = TRUE)
DUYAG1801$PAR_12 <- mean(OUTweath_UYAG1801_12$PAR, na.rm = TRUE)

DUYAG1801$RH2M_6 <- mean(OUTweath_UYAG1801_6$RH2M, na.rm = TRUE)
DUYAG1801$RH2M_9 <- mean(OUTweath_UYAG1801_9$RH2M, na.rm = TRUE)
DUYAG1801$RH2M_12 <- mean(OUTweath_UYAG1801_12$RH2M, na.rm = TRUE)

DUYAG1801$WIND_6 <- mean(OUTweath_UYAG1801_6$WIND, na.rm = TRUE)
DUYAG1801$WIND_9 <- mean(OUTweath_UYAG1801_9$WIND, na.rm = TRUE)
DUYAG1801$WIND_12 <- mean(OUTweath_UYAG1801_12$WIND, na.rm = TRUE)

DUYAG1801$RAIN_6 <- sum(OUTweath_UYAG1801_6$RAIN)
DUYAG1801$RAIN_9 <- sum(OUTweath_UYAG1801_9$RAIN)
DUYAG1801$RAIN_12 <- sum(OUTweath_UYAG1801_12$RAIN)
```

```{r}
OUTweath_UYAG1901_6 <- OUTweath_UYAG1901 %>% slice(1:180)
OUTweath_UYAG1901_9 <- OUTweath_UYAG1901 %>% slice(181:270)
OUTweath_UYAG1901_12 <- OUTweath_UYAG1901 %>% slice(210:367)
#Merge column
DUYAG1901$TMIN_6 <- mean(OUTweath_UYAG1901_6$TMIN, na.rm = TRUE)
DUYAG1901$TMIN_9 <- mean(OUTweath_UYAG1901_9$TMIN, na.rm = TRUE)
DUYAG1901$TMIN_12 <- mean(OUTweath_UYAG1901_12$TMIN, na.rm = TRUE)

DUYAG1901$TMAX_6 <- mean(OUTweath_UYAG1901_6$TMAX, na.rm = TRUE)
DUYAG1901$TMAX_9 <- mean(OUTweath_UYAG1901_9$TMAX, na.rm = TRUE)
DUYAG1901$TMAX_12 <- mean(OUTweath_UYAG1901_12$TMAX, na.rm = TRUE)

DUYAG1901$SRAD_6 <- mean(OUTweath_UYAG1901_6$SRAD, na.rm = TRUE)
DUYAG1901$SRAD_9 <- mean(OUTweath_UYAG1901_9$SRAD, na.rm = TRUE)
DUYAG1901$SRAD_12 <- mean(OUTweath_UYAG1901_12$SRAD, na.rm = TRUE)

DUYAG1901$PAR_6 <- mean(OUTweath_UYAG1901_6$PAR, na.rm = TRUE)
DUYAG1901$PAR_9 <- mean(OUTweath_UYAG1901_9$PAR, na.rm = TRUE)
DUYAG1901$PAR_12 <- mean(OUTweath_UYAG1901_12$PAR, na.rm = TRUE)

DUYAG1901$RH2M_6 <- mean(OUTweath_UYAG1901_6$RH2M, na.rm = TRUE)
DUYAG1901$RH2M_9 <- mean(OUTweath_UYAG1901_9$RH2M, na.rm = TRUE)
DUYAG1901$RH2M_12 <- mean(OUTweath_UYAG1901_12$RH2M, na.rm = TRUE)

DUYAG1901$WIND_6 <- mean(OUTweath_UYAG1901_6$WIND, na.rm = TRUE)
DUYAG1901$WIND_9 <- mean(OUTweath_UYAG1901_9$WIND, na.rm = TRUE)
DUYAG1901$WIND_12 <- mean(OUTweath_UYAG1901_12$WIND, na.rm = TRUE)

DUYAG1901$RAIN_6 <- sum(OUTweath_UYAG1901_6$RAIN)
DUYAG1901$RAIN_9 <- sum(OUTweath_UYAG1901_9$RAIN)
DUYAG1901$RAIN_12 <- sum(OUTweath_UYAG1901_12$RAIN)
```

```{r}
OUTweath_UYIB1701_6 <- OUTweath_UYIB1701 %>% slice(1:180)
OUTweath_UYIB1701_9 <- OUTweath_UYIB1701 %>% slice(181:270)
OUTweath_UYIB1701_12 <- OUTweath_UYIB1701 %>% slice(210:366)
#Merge column
DUYIB1701$TMIN_6 <- mean(OUTweath_UYIB1701_6$TMIN, na.rm = TRUE)
DUYIB1701$TMIN_9 <- mean(OUTweath_UYIB1701_9$TMIN, na.rm = TRUE)
DUYIB1701$TMIN_12 <- mean(OUTweath_UYIB1701_12$TMIN, na.rm = TRUE)

DUYIB1701$TMAX_6 <- mean(OUTweath_UYIB1701_6$TMAX, na.rm = TRUE)
DUYIB1701$TMAX_9 <- mean(OUTweath_UYIB1701_9$TMAX, na.rm = TRUE)
DUYIB1701$TMAX_12 <- mean(OUTweath_UYIB1701_12$TMAX, na.rm = TRUE)

DUYIB1701$SRAD_6 <- mean(OUTweath_UYIB1701_6$SRAD, na.rm = TRUE)
DUYIB1701$SRAD_9 <- mean(OUTweath_UYIB1701_9$SRAD, na.rm = TRUE)
DUYIB1701$SRAD_12 <- mean(OUTweath_UYIB1701_12$SRAD, na.rm = TRUE)

DUYIB1701$PAR_6 <- mean(OUTweath_UYIB1701_6$PAR, na.rm = TRUE)
DUYIB1701$PAR_9 <- mean(OUTweath_UYIB1701_9$PAR, na.rm = TRUE)
DUYIB1701$PAR_12 <- mean(OUTweath_UYIB1701_12$PAR, na.rm = TRUE)

DUYIB1701$RH2M_6 <- mean(OUTweath_UYIB1701_6$RH2M, na.rm = TRUE)
DUYIB1701$RH2M_9 <- mean(OUTweath_UYIB1701_9$RH2M, na.rm = TRUE)
DUYIB1701$RH2M_12 <- mean(OUTweath_UYIB1701_12$RH2M, na.rm = TRUE)

DUYIB1701$WIND_6 <- mean(OUTweath_UYIB1701_6$WIND, na.rm = TRUE)
DUYIB1701$WIND_9 <- mean(OUTweath_UYIB1701_9$WIND, na.rm = TRUE)
DUYIB1701$WIND_12 <- mean(OUTweath_UYIB1701_12$WIND, na.rm = TRUE)

DUYIB1701$RAIN_6 <- sum(OUTweath_UYIB1701_6$RAIN)
DUYIB1701$RAIN_9 <- sum(OUTweath_UYIB1701_9$RAIN)
DUYIB1701$RAIN_12 <- sum(OUTweath_UYIB1701_12$RAIN)
```

```{r}
OUTweath_UYIB1801_6 <- OUTweath_UYIB1801 %>% slice(1:180)
OUTweath_UYIB1801_9 <- OUTweath_UYIB1801 %>% slice(181:270)
OUTweath_UYIB1801_12 <- OUTweath_UYIB1801 %>% slice(210:366)
#Merge column
DUYIB1801$TMIN_6 <- mean(OUTweath_UYIB1801_6$TMIN, na.rm = TRUE)
DUYIB1801$TMIN_9 <- mean(OUTweath_UYIB1801_9$TMIN, na.rm = TRUE)
DUYIB1801$TMIN_12 <- mean(OUTweath_UYIB1801_12$TMIN, na.rm = TRUE)

DUYIB1801$TMAX_6 <- mean(OUTweath_UYIB1801_6$TMAX, na.rm = TRUE)
DUYIB1801$TMAX_9 <- mean(OUTweath_UYIB1801_9$TMAX, na.rm = TRUE)
DUYIB1801$TMAX_12 <- mean(OUTweath_UYIB1801_12$TMAX, na.rm = TRUE)

DUYIB1801$SRAD_6 <- mean(OUTweath_UYIB1801_6$SRAD, na.rm = TRUE)
DUYIB1801$SRAD_9 <- mean(OUTweath_UYIB1801_9$SRAD, na.rm = TRUE)
DUYIB1801$SRAD_12 <- mean(OUTweath_UYIB1801_12$SRAD, na.rm = TRUE)

DUYIB1801$PAR_6 <- mean(OUTweath_UYIB1801_6$PAR, na.rm = TRUE)
DUYIB1801$PAR_9 <- mean(OUTweath_UYIB1801_9$PAR, na.rm = TRUE)
DUYIB1801$PAR_12 <- mean(OUTweath_UYIB1801_12$PAR, na.rm = TRUE)

DUYIB1801$RH2M_6 <- mean(OUTweath_UYIB1801_6$RH2M, na.rm = TRUE)
DUYIB1801$RH2M_9 <- mean(OUTweath_UYIB1801_9$RH2M, na.rm = TRUE)
DUYIB1801$RH2M_12 <- mean(OUTweath_UYIB1801_12$RH2M, na.rm = TRUE)

DUYIB1801$WIND_6 <- mean(OUTweath_UYIB1801_6$WIND, na.rm = TRUE)
DUYIB1801$WIND_9 <- mean(OUTweath_UYIB1801_9$WIND, na.rm = TRUE)
DUYIB1801$WIND_12 <- mean(OUTweath_UYIB1801_12$WIND, na.rm = TRUE)

DUYIB1801$RAIN_6 <- sum(OUTweath_UYIB1801_6$RAIN)
DUYIB1801$RAIN_9 <- sum(OUTweath_UYIB1801_9$RAIN)
DUYIB1801$RAIN_12 <- sum(OUTweath_UYIB1801_12$RAIN)
```

```{r}
OUTweath_UYIB1901_6 <- OUTweath_UYIB1901 %>% slice(1:180)
OUTweath_UYIB1901_9 <- OUTweath_UYIB1901 %>% slice(181:270)
OUTweath_UYIB1901_12 <- OUTweath_UYIB1901 %>% slice(210:341)
#Merge column
DUYIB1901$TMIN_6 <- mean(OUTweath_UYIB1901_6$TMIN, na.rm = TRUE)
DUYIB1901$TMIN_9 <- mean(OUTweath_UYIB1901_9$TMIN, na.rm = TRUE)
DUYIB1901$TMIN_12 <- mean(OUTweath_UYIB1901_12$TMIN, na.rm = TRUE)

DUYIB1901$TMAX_6 <- mean(OUTweath_UYIB1901_6$TMAX, na.rm = TRUE)
DUYIB1901$TMAX_9 <- mean(OUTweath_UYIB1901_9$TMAX, na.rm = TRUE)
DUYIB1901$TMAX_12 <- mean(OUTweath_UYIB1901_12$TMAX, na.rm = TRUE)

DUYIB1901$SRAD_6 <- mean(OUTweath_UYIB1901_6$SRAD, na.rm = TRUE)
DUYIB1901$SRAD_9 <- mean(OUTweath_UYIB1901_9$SRAD, na.rm = TRUE)
DUYIB1901$SRAD_12 <- mean(OUTweath_UYIB1901_12$SRAD, na.rm = TRUE)

DUYIB1901$PAR_6 <- mean(OUTweath_UYIB1901_6$PAR, na.rm = TRUE)
DUYIB1901$PAR_9 <- mean(OUTweath_UYIB1901_9$PAR, na.rm = TRUE)
DUYIB1901$PAR_12 <- mean(OUTweath_UYIB1901_12$PAR, na.rm = TRUE)

DUYIB1901$RH2M_6 <- mean(OUTweath_UYIB1901_6$RH2M, na.rm = TRUE)
DUYIB1901$RH2M_9 <- mean(OUTweath_UYIB1901_9$RH2M, na.rm = TRUE)
DUYIB1901$RH2M_12 <- mean(OUTweath_UYIB1901_12$RH2M, na.rm = TRUE)

DUYIB1901$WIND_6 <- mean(OUTweath_UYIB1901_6$WIND, na.rm = TRUE)
DUYIB1901$WIND_9 <- mean(OUTweath_UYIB1901_9$WIND, na.rm = TRUE)
DUYIB1901$WIND_12 <- mean(OUTweath_UYIB1901_12$WIND, na.rm = TRUE)

DUYIB1901$RAIN_6 <- sum(OUTweath_UYIB1901_6$RAIN)
DUYIB1901$RAIN_9 <- sum(OUTweath_UYIB1901_9$RAIN)
DUYIB1901$RAIN_12 <- sum(OUTweath_UYIB1901_12$RAIN)
```


```{r}
OUTweath_UYIK1701_6 <- OUTweath_UYIK1701 %>% slice(1:180)
OUTweath_UYIK1701_9 <- OUTweath_UYIK1701 %>% slice(181:270)
OUTweath_UYIK1701_12 <- OUTweath_UYIK1701 %>% slice(210:371)
#Merge column
DUYIK1701$TMIN_6 <- mean(OUTweath_UYIK1701_6$TMIN, na.rm = TRUE)
DUYIK1701$TMIN_9 <- mean(OUTweath_UYIK1701_9$TMIN, na.rm = TRUE)
DUYIK1701$TMIN_12 <- mean(OUTweath_UYIK1701_12$TMIN, na.rm = TRUE)

DUYIK1701$TMAX_6 <- mean(OUTweath_UYIK1701_6$TMAX, na.rm = TRUE)
DUYIK1701$TMAX_9 <- mean(OUTweath_UYIK1701_9$TMAX, na.rm = TRUE)
DUYIK1701$TMAX_12 <- mean(OUTweath_UYIK1701_12$TMAX, na.rm = TRUE)

DUYIK1701$SRAD_6 <- mean(OUTweath_UYIK1701_6$SRAD, na.rm = TRUE)
DUYIK1701$SRAD_9 <- mean(OUTweath_UYIK1701_9$SRAD, na.rm = TRUE)
DUYIK1701$SRAD_12 <- mean(OUTweath_UYIK1701_12$SRAD, na.rm = TRUE)

DUYIK1701$PAR_6 <- mean(OUTweath_UYIK1701_6$PAR, na.rm = TRUE)
DUYIK1701$PAR_9 <- mean(OUTweath_UYIK1701_9$PAR, na.rm = TRUE)
DUYIK1701$PAR_12 <- mean(OUTweath_UYIK1701_12$PAR, na.rm = TRUE)

DUYIK1701$RH2M_6 <- mean(OUTweath_UYIK1701_6$RH2M, na.rm = TRUE)
DUYIK1701$RH2M_9 <- mean(OUTweath_UYIK1701_9$RH2M, na.rm = TRUE)
DUYIK1701$RH2M_12 <- mean(OUTweath_UYIK1701_12$RH2M, na.rm = TRUE)

DUYIK1701$WIND_6 <- mean(OUTweath_UYIK1701_6$WIND, na.rm = TRUE)
DUYIK1701$WIND_9 <- mean(OUTweath_UYIK1701_9$WIND, na.rm = TRUE)
DUYIK1701$WIND_12 <- mean(OUTweath_UYIK1701_12$WIND, na.rm = TRUE)

DUYIK1701$RAIN_6 <- sum(OUTweath_UYIK1701_6$RAIN)
DUYIK1701$RAIN_9 <- sum(OUTweath_UYIK1701_9$RAIN)
DUYIK1701$RAIN_12 <- sum(OUTweath_UYIK1701_12$RAIN)
```

```{r}
OUTweath_UYIK1801_6 <- OUTweath_UYIK1801 %>% slice(1:180)
OUTweath_UYIK1801_9 <- OUTweath_UYIK1801 %>% slice(181:270)
OUTweath_UYIK1801_12 <- OUTweath_UYIK1801 %>% slice(210:366)
#Merge column
DUYIK1801$TMIN_6 <- mean(OUTweath_UYIK1801_6$TMIN, na.rm = TRUE)
DUYIK1801$TMIN_9 <- mean(OUTweath_UYIK1801_9$TMIN, na.rm = TRUE)
DUYIK1801$TMIN_12 <- mean(OUTweath_UYIK1801_12$TMIN, na.rm = TRUE)

DUYIK1801$TMAX_6 <- mean(OUTweath_UYIK1801_6$TMAX, na.rm = TRUE)
DUYIK1801$TMAX_9 <- mean(OUTweath_UYIK1801_9$TMAX, na.rm = TRUE)
DUYIK1801$TMAX_12 <- mean(OUTweath_UYIK1801_12$TMAX, na.rm = TRUE)

DUYIK1801$SRAD_6 <- mean(OUTweath_UYIK1801_6$SRAD, na.rm = TRUE)
DUYIK1801$SRAD_9 <- mean(OUTweath_UYIK1801_9$SRAD, na.rm = TRUE)
DUYIK1801$SRAD_12 <- mean(OUTweath_UYIK1801_12$SRAD, na.rm = TRUE)

DUYIK1801$PAR_6 <- mean(OUTweath_UYIK1801_6$PAR, na.rm = TRUE)
DUYIK1801$PAR_9 <- mean(OUTweath_UYIK1801_9$PAR, na.rm = TRUE)
DUYIK1801$PAR_12 <- mean(OUTweath_UYIK1801_12$PAR, na.rm = TRUE)

DUYIK1801$RH2M_6 <- mean(OUTweath_UYIK1801_6$RH2M, na.rm = TRUE)
DUYIK1801$RH2M_9 <- mean(OUTweath_UYIK1801_9$RH2M, na.rm = TRUE)
DUYIK1801$RH2M_12 <- mean(OUTweath_UYIK1801_12$RH2M, na.rm = TRUE)

DUYIK1801$WIND_6 <- mean(OUTweath_UYIK1801_6$WIND, na.rm = TRUE)
DUYIK1801$WIND_9 <- mean(OUTweath_UYIK1801_9$WIND, na.rm = TRUE)
DUYIK1801$WIND_12 <- mean(OUTweath_UYIK1801_12$WIND, na.rm = TRUE)

DUYIK1801$RAIN_6 <- sum(OUTweath_UYIK1801_6$RAIN)
DUYIK1801$RAIN_9 <- sum(OUTweath_UYIK1801_9$RAIN)
DUYIK1801$RAIN_12 <- sum(OUTweath_UYIK1801_12$RAIN)
```

```{r}
OUTweath_UYIK1901_6 <- OUTweath_UYIK1901 %>% slice(1:180)
OUTweath_UYIK1901_9 <- OUTweath_UYIK1901 %>% slice(181:270)
OUTweath_UYIK1901_12 <- OUTweath_UYIK1901 %>% slice(210:381)
#Merge column
DUYIK1901$TMIN_6 <- mean(OUTweath_UYIK1901_6$TMIN, na.rm = TRUE)
DUYIK1901$TMIN_9 <- mean(OUTweath_UYIK1901_9$TMIN, na.rm = TRUE)
DUYIK1901$TMIN_12 <- mean(OUTweath_UYIK1901_12$TMIN, na.rm = TRUE)

DUYIK1901$TMAX_6 <- mean(OUTweath_UYIK1901_6$TMAX, na.rm = TRUE)
DUYIK1901$TMAX_9 <- mean(OUTweath_UYIK1901_9$TMAX, na.rm = TRUE)
DUYIK1901$TMAX_12 <- mean(OUTweath_UYIK1901_12$TMAX, na.rm = TRUE)

DUYIK1901$SRAD_6 <- mean(OUTweath_UYIK1901_6$SRAD, na.rm = TRUE)
DUYIK1901$SRAD_9 <- mean(OUTweath_UYIK1901_9$SRAD, na.rm = TRUE)
DUYIK1901$SRAD_12 <- mean(OUTweath_UYIK1901_12$SRAD, na.rm = TRUE)

DUYIK1901$PAR_6 <- mean(OUTweath_UYIK1901_6$PAR, na.rm = TRUE)
DUYIK1901$PAR_9 <- mean(OUTweath_UYIK1901_9$PAR, na.rm = TRUE)
DUYIK1901$PAR_12 <- mean(OUTweath_UYIK1901_12$PAR, na.rm = TRUE)

DUYIK1901$RH2M_6 <- mean(OUTweath_UYIK1901_6$RH2M, na.rm = TRUE)
DUYIK1901$RH2M_9 <- mean(OUTweath_UYIK1901_9$RH2M, na.rm = TRUE)
DUYIK1901$RH2M_12 <- mean(OUTweath_UYIK1901_12$RH2M, na.rm = TRUE)

DUYIK1901$WIND_6 <- mean(OUTweath_UYIK1901_6$WIND, na.rm = TRUE)
DUYIK1901$WIND_9 <- mean(OUTweath_UYIK1901_9$WIND, na.rm = TRUE)
DUYIK1901$WIND_12 <- mean(OUTweath_UYIK1901_12$WIND, na.rm = TRUE)

DUYIK1901$RAIN_6 <- sum(OUTweath_UYIK1901_6$RAIN)
DUYIK1901$RAIN_9 <- sum(OUTweath_UYIK1901_9$RAIN)
DUYIK1901$RAIN_12 <- sum(OUTweath_UYIK1901_12$RAIN)
```

```{r}
OUTweath_UYMO1701_6 <- OUTweath_UYMO1701 %>% slice(1:180)
OUTweath_UYMO1701_9 <- OUTweath_UYMO1701 %>% slice(181:270)
OUTweath_UYMO1701_12 <- OUTweath_UYMO1701 %>% slice(210:406)
#Merge column
DUYMO1701$TMIN_6 <- mean(OUTweath_UYMO1701_6$TMIN, na.rm = TRUE)
DUYMO1701$TMIN_9 <- mean(OUTweath_UYMO1701_9$TMIN, na.rm = TRUE)
DUYMO1701$TMIN_12 <- mean(OUTweath_UYMO1701_12$TMIN, na.rm = TRUE)

DUYMO1701$TMAX_6 <- mean(OUTweath_UYMO1701_6$TMAX, na.rm = TRUE)
DUYMO1701$TMAX_9 <- mean(OUTweath_UYMO1701_9$TMAX, na.rm = TRUE)
DUYMO1701$TMAX_12 <- mean(OUTweath_UYMO1701_12$TMAX, na.rm = TRUE)

DUYMO1701$SRAD_6 <- mean(OUTweath_UYMO1701_6$SRAD, na.rm = TRUE)
DUYMO1701$SRAD_9 <- mean(OUTweath_UYMO1701_9$SRAD, na.rm = TRUE)
DUYMO1701$SRAD_12 <- mean(OUTweath_UYMO1701_12$SRAD, na.rm = TRUE)

DUYMO1701$PAR_6 <- mean(OUTweath_UYMO1701_6$PAR, na.rm = TRUE)
DUYMO1701$PAR_9 <- mean(OUTweath_UYMO1701_9$PAR, na.rm = TRUE)
DUYMO1701$PAR_12 <- mean(OUTweath_UYMO1701_12$PAR, na.rm = TRUE)

DUYMO1701$RH2M_6 <- mean(OUTweath_UYMO1701_6$RH2M, na.rm = TRUE)
DUYMO1701$RH2M_9 <- mean(OUTweath_UYMO1701_9$RH2M, na.rm = TRUE)
DUYMO1701$RH2M_12 <- mean(OUTweath_UYMO1701_12$RH2M, na.rm = TRUE)

DUYMO1701$WIND_6 <- mean(OUTweath_UYMO1701_6$WIND, na.rm = TRUE)
DUYMO1701$WIND_9 <- mean(OUTweath_UYMO1701_9$WIND, na.rm = TRUE)
DUYMO1701$WIND_12 <- mean(OUTweath_UYMO1701_12$WIND, na.rm = TRUE)

DUYMO1701$RAIN_6 <- sum(OUTweath_UYMO1701_6$RAIN)
DUYMO1701$RAIN_9 <- sum(OUTweath_UYMO1701_9$RAIN)
DUYMO1701$RAIN_12 <- sum(OUTweath_UYMO1701_12$RAIN)
```


```{r}
OUTweath_UYMO1801_6 <- OUTweath_UYMO1801 %>% slice(1:180)
OUTweath_UYMO1801_9 <- OUTweath_UYMO1801 %>% slice(181:270)
OUTweath_UYMO1801_12 <- OUTweath_UYMO1801 %>% slice(210:366)
#Merge column
DUYMO1801$TMIN_6 <- mean(OUTweath_UYMO1801_6$TMIN, na.rm = TRUE)
DUYMO1801$TMIN_9 <- mean(OUTweath_UYMO1801_9$TMIN, na.rm = TRUE)
DUYMO1801$TMIN_12 <- mean(OUTweath_UYMO1801_12$TMIN, na.rm = TRUE)

DUYMO1801$TMAX_6 <- mean(OUTweath_UYMO1801_6$TMAX, na.rm = TRUE)
DUYMO1801$TMAX_9 <- mean(OUTweath_UYMO1801_9$TMAX, na.rm = TRUE)
DUYMO1801$TMAX_12 <- mean(OUTweath_UYMO1801_12$TMAX, na.rm = TRUE)

DUYMO1801$SRAD_6 <- mean(OUTweath_UYMO1801_6$SRAD, na.rm = TRUE)
DUYMO1801$SRAD_9 <- mean(OUTweath_UYMO1801_9$SRAD, na.rm = TRUE)
DUYMO1801$SRAD_12 <- mean(OUTweath_UYMO1801_12$SRAD, na.rm = TRUE)

DUYMO1801$PAR_6 <- mean(OUTweath_UYMO1801_6$PAR, na.rm = TRUE)
DUYMO1801$PAR_9 <- mean(OUTweath_UYMO1801_9$PAR, na.rm = TRUE)
DUYMO1801$PAR_12 <- mean(OUTweath_UYMO1801_12$PAR, na.rm = TRUE)

DUYMO1801$RH2M_6 <- mean(OUTweath_UYMO1801_6$RH2M, na.rm = TRUE)
DUYMO1801$RH2M_9 <- mean(OUTweath_UYMO1801_9$RH2M, na.rm = TRUE)
DUYMO1801$RH2M_12 <- mean(OUTweath_UYMO1801_12$RH2M, na.rm = TRUE)

DUYMO1801$WIND_6 <- mean(OUTweath_UYMO1801_6$WIND, na.rm = TRUE)
DUYMO1801$WIND_9 <- mean(OUTweath_UYMO1801_9$WIND, na.rm = TRUE)
DUYMO1801$WIND_12 <- mean(OUTweath_UYMO1801_12$WIND, na.rm = TRUE)

DUYMO1801$RAIN_6 <- sum(OUTweath_UYMO1801_6$RAIN)
DUYMO1801$RAIN_9 <- sum(OUTweath_UYMO1801_9$RAIN)
DUYMO1801$RAIN_12 <- sum(OUTweath_UYMO1801_12$RAIN)
```

```{r}
OUTweath_UYMO1901_6 <- OUTweath_UYMO1901 %>% slice(1:180)
OUTweath_UYMO1901_9 <- OUTweath_UYMO1901 %>% slice(181:270)
OUTweath_UYMO1901_12 <- OUTweath_UYMO1901 %>% slice(210:366)
#Merge column
DUYMO1901$TMIN_6 <- mean(OUTweath_UYMO1901_6$TMIN, na.rm = TRUE)
DUYMO1901$TMIN_9 <- mean(OUTweath_UYMO1901_9$TMIN, na.rm = TRUE)
DUYMO1901$TMIN_12 <- mean(OUTweath_UYMO1901_12$TMIN, na.rm = TRUE)

DUYMO1901$TMAX_6 <- mean(OUTweath_UYMO1901_6$TMAX, na.rm = TRUE)
DUYMO1901$TMAX_9 <- mean(OUTweath_UYMO1901_9$TMAX, na.rm = TRUE)
DUYMO1901$TMAX_12 <- mean(OUTweath_UYMO1901_12$TMAX, na.rm = TRUE)

DUYMO1901$SRAD_6 <- mean(OUTweath_UYMO1901_6$SRAD, na.rm = TRUE)
DUYMO1901$SRAD_9 <- mean(OUTweath_UYMO1901_9$SRAD, na.rm = TRUE)
DUYMO1901$SRAD_12 <- mean(OUTweath_UYMO1901_12$SRAD, na.rm = TRUE)

DUYMO1901$PAR_6 <- mean(OUTweath_UYMO1901_6$PAR, na.rm = TRUE)
DUYMO1901$PAR_9 <- mean(OUTweath_UYMO1901_9$PAR, na.rm = TRUE)
DUYMO1901$PAR_12 <- mean(OUTweath_UYMO1901_12$PAR, na.rm = TRUE)

DUYMO1901$RH2M_6 <- mean(OUTweath_UYMO1901_6$RH2M, na.rm = TRUE)
DUYMO1901$RH2M_9 <- mean(OUTweath_UYMO1901_9$RH2M, na.rm = TRUE)
DUYMO1901$RH2M_12 <- mean(OUTweath_UYMO1901_12$RH2M, na.rm = TRUE)

DUYMO1901$WIND_6 <- mean(OUTweath_UYMO1901_6$WIND, na.rm = TRUE)
DUYMO1901$WIND_9 <- mean(OUTweath_UYMO1901_9$WIND, na.rm = TRUE)
DUYMO1901$WIND_12 <- mean(OUTweath_UYMO1901_12$WIND, na.rm = TRUE)

DUYMO1901$RAIN_6 <- sum(OUTweath_UYMO1901_6$RAIN)
DUYMO1901$RAIN_9 <- sum(OUTweath_UYMO1901_9$RAIN)
DUYMO1901$RAIN_12 <- sum(OUTweath_UYMO1901_12$RAIN)
```

```{r}
OUTweath_UYON1801_6 <- OUTweath_UYON1801 %>% slice(1:180)
OUTweath_UYON1801_9 <- OUTweath_UYON1801 %>% slice(181:270)
OUTweath_UYON1801_12 <- OUTweath_UYON1801 %>% slice(210:366)
#Merge column
DUYON1801$TMIN_6 <- mean(OUTweath_UYON1801_6$TMIN, na.rm = TRUE)
DUYON1801$TMIN_9 <- mean(OUTweath_UYON1801_9$TMIN, na.rm = TRUE)
DUYON1801$TMIN_12 <- mean(OUTweath_UYON1801_12$TMIN, na.rm = TRUE)

DUYON1801$TMAX_6 <- mean(OUTweath_UYON1801_6$TMAX, na.rm = TRUE)
DUYON1801$TMAX_9 <- mean(OUTweath_UYON1801_9$TMAX, na.rm = TRUE)
DUYON1801$TMAX_12 <- mean(OUTweath_UYON1801_12$TMAX, na.rm = TRUE)

DUYON1801$SRAD_6 <- mean(OUTweath_UYON1801_6$SRAD, na.rm = TRUE)
DUYON1801$SRAD_9 <- mean(OUTweath_UYON1801_9$SRAD, na.rm = TRUE)
DUYON1801$SRAD_12 <- mean(OUTweath_UYON1801_12$SRAD, na.rm = TRUE)

DUYON1801$PAR_6 <- mean(OUTweath_UYON1801_6$PAR, na.rm = TRUE)
DUYON1801$PAR_9 <- mean(OUTweath_UYON1801_9$PAR, na.rm = TRUE)
DUYON1801$PAR_12 <- mean(OUTweath_UYON1801_12$PAR, na.rm = TRUE)

DUYON1801$RH2M_6 <- mean(OUTweath_UYON1801_6$RH2M, na.rm = TRUE)
DUYON1801$RH2M_9 <- mean(OUTweath_UYON1801_9$RH2M, na.rm = TRUE)
DUYON1801$RH2M_12 <- mean(OUTweath_UYON1801_12$RH2M, na.rm = TRUE)

DUYON1801$WIND_6 <- mean(OUTweath_UYON1801_6$WIND, na.rm = TRUE)
DUYON1801$WIND_9 <- mean(OUTweath_UYON1801_9$WIND, na.rm = TRUE)
DUYON1801$WIND_12 <- mean(OUTweath_UYON1801_12$WIND, na.rm = TRUE)

DUYON1801$RAIN_6 <- sum(OUTweath_UYON1801_6$RAIN)
DUYON1801$RAIN_9 <- sum(OUTweath_UYON1801_9$RAIN)
DUYON1801$RAIN_12 <- sum(OUTweath_UYON1801_12$RAIN)
```


```{r}
OUTweath_UYUB1901_6 <- OUTweath_UYUB1901 %>% slice(1:180)
OUTweath_UYUB1901_9 <- OUTweath_UYUB1901 %>% slice(181:270)
OUTweath_UYUB1901_12 <- OUTweath_UYUB1901 %>% slice(210:370)
#Merge column
DUYUB1901$TMIN_6 <- mean(OUTweath_UYUB1901_6$TMIN, na.rm = TRUE)
DUYUB1901$TMIN_9 <- mean(OUTweath_UYUB1901_9$TMIN, na.rm = TRUE)
DUYUB1901$TMIN_12 <- mean(OUTweath_UYUB1901_12$TMIN, na.rm = TRUE)

DUYUB1901$TMAX_6 <- mean(OUTweath_UYUB1901_6$TMAX, na.rm = TRUE)
DUYUB1901$TMAX_9 <- mean(OUTweath_UYUB1901_9$TMAX, na.rm = TRUE)
DUYUB1901$TMAX_12 <- mean(OUTweath_UYUB1901_12$TMAX, na.rm = TRUE)

DUYUB1901$SRAD_6 <- mean(OUTweath_UYUB1901_6$SRAD, na.rm = TRUE)
DUYUB1901$SRAD_9 <- mean(OUTweath_UYUB1901_9$SRAD, na.rm = TRUE)
DUYUB1901$SRAD_12 <- mean(OUTweath_UYUB1901_12$SRAD, na.rm = TRUE)

DUYUB1901$PAR_6 <- mean(OUTweath_UYUB1901_6$PAR, na.rm = TRUE)
DUYUB1901$PAR_9 <- mean(OUTweath_UYUB1901_9$PAR, na.rm = TRUE)
DUYUB1901$PAR_12 <- mean(OUTweath_UYUB1901_12$PAR, na.rm = TRUE)

DUYUB1901$RH2M_6 <- mean(OUTweath_UYUB1901_6$RH2M, na.rm = TRUE)
DUYUB1901$RH2M_9 <- mean(OUTweath_UYUB1901_9$RH2M, na.rm = TRUE)
DUYUB1901$RH2M_12 <- mean(OUTweath_UYUB1901_12$RH2M, na.rm = TRUE)

DUYUB1901$WIND_6 <- mean(OUTweath_UYUB1901_6$WIND, na.rm = TRUE)
DUYUB1901$WIND_9 <- mean(OUTweath_UYUB1901_9$WIND, na.rm = TRUE)
DUYUB1901$WIND_12 <- mean(OUTweath_UYUB1901_12$WIND, na.rm = TRUE)

DUYUB1901$RAIN_6 <- sum(OUTweath_UYUB1901_6$RAIN)
DUYUB1901$RAIN_9 <- sum(OUTweath_UYUB1901_9$RAIN)
DUYUB1901$RAIN_12 <- sum(OUTweath_UYUB1901_12$RAIN)
```

```{r}
OUTweath_UYUM1801_6 <- OUTweath_UYUM1801 %>% slice(1:180)
OUTweath_UYUM1801_9 <- OUTweath_UYUM1801 %>% slice(181:270)
OUTweath_UYUM1801_12 <- OUTweath_UYUM1801 %>% slice(210:366)
#Merge column
DUYUM1801$TMIN_6 <- mean(OUTweath_UYUM1801_6$TMIN, na.rm = TRUE)
DUYUM1801$TMIN_9 <- mean(OUTweath_UYUM1801_9$TMIN, na.rm = TRUE)
DUYUM1801$TMIN_12 <- mean(OUTweath_UYUM1801_12$TMIN, na.rm = TRUE)

DUYUM1801$TMAX_6 <- mean(OUTweath_UYUM1801_6$TMAX, na.rm = TRUE)
DUYUM1801$TMAX_9 <- mean(OUTweath_UYUM1801_9$TMAX, na.rm = TRUE)
DUYUM1801$TMAX_12 <- mean(OUTweath_UYUM1801_12$TMAX, na.rm = TRUE)

DUYUM1801$SRAD_6 <- mean(OUTweath_UYUM1801_6$SRAD, na.rm = TRUE)
DUYUM1801$SRAD_9 <- mean(OUTweath_UYUM1801_9$SRAD, na.rm = TRUE)
DUYUM1801$SRAD_12 <- mean(OUTweath_UYUM1801_12$SRAD, na.rm = TRUE)

DUYUM1801$PAR_6 <- mean(OUTweath_UYUM1801_6$PAR, na.rm = TRUE)
DUYUM1801$PAR_9 <- mean(OUTweath_UYUM1801_9$PAR, na.rm = TRUE)
DUYUM1801$PAR_12 <- mean(OUTweath_UYUM1801_12$PAR, na.rm = TRUE)

DUYUM1801$RH2M_6 <- mean(OUTweath_UYUM1801_6$RH2M, na.rm = TRUE)
DUYUM1801$RH2M_9 <- mean(OUTweath_UYUM1801_9$RH2M, na.rm = TRUE)
DUYUM1801$RH2M_12 <- mean(OUTweath_UYUM1801_12$RH2M, na.rm = TRUE)

DUYUM1801$WIND_6 <- mean(OUTweath_UYUM1801_6$WIND, na.rm = TRUE)
DUYUM1801$WIND_9 <- mean(OUTweath_UYUM1801_9$WIND, na.rm = TRUE)
DUYUM1801$WIND_12 <- mean(OUTweath_UYUM1801_12$WIND, na.rm = TRUE)

DUYUM1801$RAIN_6 <- sum(OUTweath_UYUM1801_6$RAIN)
DUYUM1801$RAIN_9 <- sum(OUTweath_UYUM1801_9$RAIN)
DUYUM1801$RAIN_12 <- sum(OUTweath_UYUM1801_12$RAIN)
```



```{r}
#get all the evaluate Output
GLUEVAL2 <- bind_rows(Abuja19 = DUYAB1901, Ago17 = DUYAG1701, Ago18 = DUYAG1801, Ago19 = DUYAG1901, Ibadan17 = DUYIB1701, Ibadan18 = DUYIB1801, Ibadan19 = DUYIB1901, Ikenne17 = DUYIK1701, Ikenne18 = DUYIK1801, Ikenne19 = DUYIK1901,  Mokwa17 = DUYMO1701, Mokwa18 = DUYMO1801, Mokwa19 = DUYMO1901, Onne18 = DUYON1801,  Ubiaja19 = DUYUB1901, Umudike18 = DUYUM1801, .id = "source") %>% #Zaria19 = DUYZA1901, Otobi18 = DUYOT1801, Kano18 = DUYKA1801,
       mutate(HWAMMS = HWAMM - HWAMS,
              HWAMMSsq = (HWAMM - HWAMS)^2) 
colnames(GLUEVAL2)
GLUEVAL2$year <- as.numeric(paste0("20", str_extract(GLUEVAL2$source, "\\d{2}+")))
write.csv(GLUEVAL2, "data/GLUEVALana2.csv", quote = F, row.names = F) 
```


#PRcomp using Prcomp to
```{r}
#library(FactoMineR); library(factoextra); library(corrplot); library(stats)
#PRINpca <- princomp(PRdata, cor = FALSE, scores = TRUE)
#summary(PRINpca)
#PRpca <- prcomp(PRdata, center = TRUE, scale = TRUE, na.omit=)
#summary(PRpca)
#PRval <- get_eigenvalue(PRpca)
#PRval
#fviz_eig(PRpca, addlabels = TRUE, ylim = c(0, 50))
# For variables
#PRvar <- get_pca_var(PRpca)
#PRvar$coord          # coordinates of variables to create a scatter plot
#PRvar$contrib        # contains the contributions (in percentage) of the variables to the principal components. The contribution of a variable (var) to a given principal component is (in percentage) : (var.cos2 * 100) / (total cos2 of the component).
#PRvar$cos2           # represents the quality of representation for variables on the factor map. Its calculated as the squared coordinates: var.cos2 = var.coord * var.coord. 
#write.csv(PRvar$cos2, "result/PRvarcos.csv")
#corrplot(PRvar$contrib, is.corr=FALSE)
#fviz_pca_var(PRpca, col.var = "contrib",
 #            gradient.cols = c("#00AFBB", "#E7B800", "#FC4E07"))

# Results for individuals
#PRind <- get_pca_ind(PRpca)
#PRind
#PRind$coord   
#PRind$contrib       
#PRind$cos2 
#write.csv(PRind$cos2, "result/PRindcossim.csv")
#fviz_pca_ind(PRpca, col.ind = "contrib", 
#             gradient.cols = c("#00AFBB", "#E7B800", "#FC4E07"),
 #            repel = TRUE # Avoid text overlapping (slow if many points)
  #           )
# Total contribution on PC1 and PC2
#fviz_contrib(PRpca, choice = "ind", axes = 1:2, top = 20)
#corrplot(PRind$contrib, is.corr=FALSE)
#corrplot(PRind$cos2, is.corr=FALSE)
```

#For princomp
```{r}
#PRinpca <- princomp(PRdata, cor = FALSE, scores = TRUE, na.action = na.omit)
#summary(PRinpca)
#PRval <- get_eigenvalue(PRpca)
#PRval
#fviz_eig(PRpca, addlabels = TRUE, ylim = c(0, 50))
# For variables
#PRvar <- get_pca_var(PRpca)
#PRvar$coord          # coordinates of variables to create a scatter plot
#PRvar$contrib        # contains the contributions (in percentage) of the variables to the principal components. The contribution of a variable (var) to a given principal component is (in percentage) : (var.cos2 * 100) / (total cos2 of the component).
#PRvar$cos2           # represents the quality of representation for variables on the factor map. Its calculated as the squared coordinates: var.cos2 = var.coord * var.coord. 


#corrplot(PRvar$cos2, is.corr=FALSE)

```

