---
title: "trialcheck"
author: "Opamelas83"
date: "2022-03-23"
output: workflowr::wflow_html
editor_options:
  chunk_output_type: console
---

## Read GXE trials

```{r}
colClasses <- readr::read_csv(here::here("data/IITA2021_CABASE", "colClasses.csv"))
# colClasses[14, 2] <- colClasses[15, 2] <- "Date"
colString <- paste0(substring(colClasses$colClass, 1, 1), collapse="")
uytAllM <- readr::read_csv(here::here("data/IITA2021_CABASE", "UYT_GXE_pheno.csv"), 
                                     col_types=colString)
#colnames(uytAllM)
#trials <- uytAll %>% distinct(studyYear, locationName)
```

```{r}
Start1 <- uytAllM %>% mutate(Year = studyYear,
               Clone = germplasmName) %>%
      rename(Pharperplot = "plant stands harvested counting|CO_334:0000010",
        HWAM = "fresh storage root weight per plot|CO_334:0000012",
            CWAM = "fresh shoot weight measurement in kg per plot|CO_334:0000016") %>%
        dplyr::select(locationName, germplasmName, Year, HWAM, CWAM, Pharperplot) %>%
         filter(!is.na(HWAM))
Start2 <- Start1 %>% filter(Pharperplot > 15)

oooo <- Start2 %>% group_by(Year, locationName, Pharperplot) %>%
      summarise(nb = n())

unique(Start2$locationName)  
  

count(Start2, HWAM = O)
plot(Start2$Pharperplot, Start2$HWAM)
mean(Start2$HWAM)
unique(Start1$locationName)
```

##check trials by location by year
```{r}

```



```{r}
#row.names(uytAllM)
uytAllche1 <- uytAllM %>% 
        mutate(Mtrial = row.names(uytAllM),
               Year = studyYear,
               Clone = germplasmName) %>%
      rename(FRoot = "fresh storage root weight per plot|CO_334:0000012",
    FTop = "fresh shoot weight measurement in kg per plot|CO_334:0000016") %>%
        select(Mtrial, locationName, Year, FRoot, FTop )

plot(uytAllche1$FRoot)
#Plot by location
```

```{r}
uytAllM %>% 
      count(studyYear,studyName,studyDesign,plotWidth,plotLength,plantsPerPlot) %>% 
     mutate(plotArea=plotWidth*plotLength) %>% 
     gt() %>% tab_options(table.font.size = pct(67))
```


look at the min, mean and max number of accessions per blockNumber.
```{r}
dbdata %>% 
     group_by(studyName) %>% 
     summarize(N_accession=length(unique(germplasmName))) %>% 
     left_join(dbdata %>% 
     group_by(studyName,replicate,blockNumber) %>% 
     summarize(N_accession=length(unique(germplasmName))) %>% ungroup() %>% 
     group_by(studyName) %>% 
     summarize(minAccessionsPerBlock=ceiling(min(N_accession)),
               avgAccessionsPerBlock=ceiling(mean(N_accession)),
               maxAccessionsPerBlock=ceiling(max(N_accession)))) %>% 
     gt() %>% tab_options(table.font.size = pct(60))
```


